### ISSUE TITLE
Error while Uploading Lambda Function to S3 in Lambda Dialog Box 

### ISSUE THREAD

**Issue by iamfool** [aws/aws-toolkit-eclipse#108]
I am getting an java pkix path building failed exception while trying to upload my lambda function to S3 in dialog box.

Somebody please help, this use to work before not sure what happened in the background. I even tried to update the toolkit with latest update. No luck. I also tried adding aws certificate into jre cacert. Nothing worked.

**Comment by zhangzhx** [comment]
It seems you didn't configure the certificate correctly to your JRE. Take a look at this to see if it helps:

http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html

**Comment by kiiadi** [comment]
Let us know if you need any further assistance - closing for now.
