### ISSUE TITLE
Unable to create an AWS java Project

### ISSUE THREAD

**Issue by jayadityan** [aws/aws-toolkit-eclipse#110]
After installing the AWS toolkit from Eclipse Market place, Getting the below error in case of creating a new AWS Java Project. 

![image](https://user-images.githubusercontent.com/37784423/41075016-12639354-6a4e-11e8-9b55-e37ca906a8a5.png)

**Comment by zhangzhx** [comment]
Can you share more context about the failure of project creation? What platform are you using? Is the 1234 project name you are creating?

**Comment by zhangzhx** [comment]
Closing this issue due to no response for a long time. Feel free to reopen it if you have more questions.

**Comment by rambabu-vempadapu** [comment]
I am using the java 1.8 maven 3.5.and when i am tryingto crearte a aws java project i ma getting the error

**Comment by rambabu-vempadapu** [comment]
![Screenshot from 2019-08-02 20-32-09](https://user-images.githubusercontent.com/48059675/62379448-a0c2f880-b564-11e9-8b2c-a879cee10131.png)

**Comment by rambabu-vempadapu** [comment]
issues is resolved there was an issues with my maven , i have updated the windows>preference>maven>usersetting and the the settings.xml file and it worked
