### ISSUE TITLE
Extensible Menu itemis

### ISSUE THREAD

**Issue by grafandreas** [aws/aws-toolkit-eclipse#112]
Dear AWS Team,

it seems that there are no possibilities for extending the existing menus on the EC2 instances explorer. We would like to develop a 3rd party plugin that provides tighter integration to the Eclipse RSE and TM projects.

Would you be interested in a contribution, that makes the AWS instance explorer pop-up extensible by standard Eclipse means?

Regards,

Andreas

**Comment by zhangzhx** [comment]
The AWS Toolkit plugin is not designed to be extended by third party. You are definitely welcome to make a contribution. Feel free to send a RP and we'd like to review it. :)

**Comment by zhangzhx** [comment]
Closing this issue due to no response for a long time. Feel free to reopen it if you still have more questions.
