### ISSUE TITLE
I cannot create S3 bucket for function code.

### ISSUE THREAD

**Issue by truonguit2010** [aws/aws-toolkit-eclipse#114]
Hello,

I cannot create the S3 bucket for function code in Eclipse. How can I resolve this problem?

Failed to load bucket in Asia Pacific (Singapore): com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 6676194916D20ACA; S3 Extended Request ID: WGyJfNvYhmZOOYyoLVj7bk6Fy7O6ebJqVL9RoFowR/2S3u50gBI7sDAOq4x9uZL0NDjF1u5C644=

![alt text](https://image.ibb.co/bBPV4d/Lambda.png "Logo Title Text 1")

Thank you very much,
Truong Pham Son

**Comment by zhangzhx** [comment]
Please double check your AWS credentials to see if you have permission to access S3 bucket. From the error message, it seems that you don't have the permission to create a new S3 bucket.

**Comment by zhangzhx** [comment]
Closing this issue due to no response for a long time. Feel free to reopen it if you have more questions.

**Comment by deydeepankar2012** [comment]
@zhangzhx Even i am getting the same issue. Neither i am able to create bucket nor it loads already existing buckets. Below is the user policy 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iam:CreateRole",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "iam:ListRoles",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*****-lambda-bucket"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "s3:*Object",
            "Resource": [
                "arn:aws:s3:::*****-lambda-bucket/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*****-lambda-bucket"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "s3:*Object",
            "Resource": [
                "arn:aws:s3:::*****-lambda-bucket/*"
            ]
        }
    ]
}

**Comment by zhangzhx** [comment]
Hey @deydeepankar2012 , it seems that you do not have `S3:CreateBucket` permission defined in your IAM policy. Also, in the policy, the `S3:ListBucket` only have access to the only bucket `arn:aws:s3:::-lambda-bucket`. You should add `S3:CreateBucket` permission for creating bucket.

**Comment by deydeepankar2012** [comment]
{
"Action":"s3:CreateBucket",
"Effect":"Allow",
"Resource":"*"
}
Adding this policy is letting me create bucket. But I am still unable to list all the existing buckets from the selected region.

**Comment by deydeepankar2012** [comment]
I am getting the below error when i try to upload project to lambda.
Failed to upload project to Lambda
Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 3406D22ED93E5CAE; S3 Extended Request ID: XaWqcstsPLx5LJFC2qvIFzE6TO8DT2NSxQNSG/R+Hd32Dsqsj43cQLJk8ihKXYC3Reh+JciLAVU=)

**Comment by deydeepankar2012** [comment]
After a lot of tinkering the below approach worked for me.

Go to S3. Select your bucket that was created from eclipse aws toolkit. Click Permissions. Click Bucket Policy and then add this : 

{
    "Version": "2012-10-17",
    "Id": "Lambda access bucket policy",
    "Statement": [
        {
            "Sid": "All on objects in bucket lambda",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::AWSACCOUNTID:root"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::BUCKET-NAME/*"
        },
        {
            "Sid": "All on bucket by lambda",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::AWSACCOUNTID:root"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::BUCKET-NAME"
        }
    ]
}
Add below policy for the user : 

**{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iam:CreateRole",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "iam:ListRoles",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:CreateBucket",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "lambda:CreateFunction",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:*Object",
            "Resource": "*"
        },
        {
            "Sid": "PassExecutionRole",
            "Effect": "Allow",
            "Action": [
                "iam:ListRolePolicies",
                "iam:ListAttachedRolePolicies",
                "iam:GetRole",
                "iam:PassRole"
            ],
            "Resource": "*"
        },
    ]
}**

**Comment by zhangzhx** [comment]
Glad you figured out. The root cause of this access denied exception is that you didn't configure the IAM policy correctly for createBucket and listBuckets. Now that in your new version of the policy, you added those permissions which is why it is working now. :)
