### ISSUE TITLE
downloaded the toolkit, but cannot install

### ISSUE THREAD

**Issue by ghost** [aws/aws-toolkit-eclipse#121]
Hi, 

 I have downloaded the toolkit from git, but when i was installing a new software into eclipse, i am facing some issue. where the eclipse could not find the file, in my folder where i have unzip the zip file that i have just downloaded from git. 

Thanks.

**Comment by zhangzhx** [comment]
Can you elaborate the problem step by step? Also, we'd recommend you install the plugin from the update site http://aws.amazon.com/eclipse

**Comment by zhangzhx** [comment]
Not hearing back for a long time, closing this issue for now. Feel free to reopen if you still have problem.
