### ISSUE TITLE
Can't install through Eclipse Marketplace

### ISSUE THREAD

**Issue by FredDeschenes** [aws/aws-toolkit-eclipse#127]
As the title says, installation through the Eclipse Marketplace is currently broken. I can see the plugin, click "Install", see and select features, but clicking "Confirm" to run the installation gives me the following error : 
```
Unable to read repository at http://aws.amazon.com/eclipse/site.xml/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Relevant info:
- Windows 10
- OpenJDK 10.0.2
- Eclipse Oxygen

**Comment by FredDeschenes** [comment]
FYI I managed to get this installed by downgrading my JDK to 1.8.0.181 (also OpenJDK).

**Comment by zhangzhx** [comment]
The current toolkit does not support Java 9+. Glad you get this installed.
