### ISSUE TITLE
Failed to Launch SAM Local with AWS Serverless Java Project hello-world blueprint

### ISSUE THREAD

**Issue by ronanore** [aws/aws-toolkit-eclipse#139]
Description of issue: 
In a fresh Eclipse IDE for Java Developers installation I have added the AWS Toolkit for Eclipse and installed Docker and SAM CLI for windows. 

When I try to run the AWS Serverless Java Project hello-world blueprint I am receiving the following error "Failed to launch SAM Local" .

However the Console did give me an output from the Lambda function. Please see the attached screenshot
![SamLocal](https://user-images.githubusercontent.com/48908176/54910231-cd467400-4ee3-11e9-883b-c5407f30462e.png)
. 

Is this an Issue with the Sample Project or is something mis-configured here? I have been unable to run this Sample Project without receiving the "Failed to launch SAM Local" error. 

Repro Steps:
-Fresh Java project.
-Install AWS toolkit for eclipse
-Install SAM CLI
-Install Docker
-Navigate to File, new, other, AWS, AWS Serverless Lambda Java Project, hello-world blueprint.
-Run Function

**Comment by zhangzhx** [comment]
Can you click the **Show Error Log** and provide the exception stack trace ?

**Comment by ronanore** [comment]
Sure:
![stacktrace](https://user-images.githubusercontent.com/48908176/54981170-90d84e00-4f9f-11e9-93b5-fee969179b3e.png)

**Comment by helmanj** [comment]
I have this exact issue currently. Any resolution?

**Comment by vinayak-kaviskar** [comment]
I am facing exact issue on ubunto 18.04, can anyody help?

**Comment by ronanore** [comment]
I ended up going with the JetBrains toolkit and had no issues with SAM Local using AWS Serverless Java Project blueprints

**Comment by atom888888** [comment]
According to this article it could have to do with the spaces in the "c:\program files" directory where SAM is installed by default (for windows).  Try replacing that sam path setting with "c:\progra~1\..." when setting up sam exe location.  I tried it and it didn't seem to help for me, but that may work for some?

https://stackoverflow.com/questions/53916879/how-to-configure-aws-sam-on-eclipse-and-window-10
