### ISSUE TITLE
Usage of the JSON schema

### ISSUE THREAD

**Issue by stevenjack** [aws/aws-toolkit-eclipse#14]
Hey guys,

I'm the maintainer of [cfndsl](https://www.github.com/stevenjack/cfndsl) (A ruby DSL for generating CF) and I was talking to a few colleagues who use your eclipse plugin. They mentioned how it's able to auto complete and validate what's entered and that started making me think that there must be a schema somewhere that it's being checked against. After having a look around your code I found this:

> [CloudFormationV1.schema](http://vstoolkit.amazonwebservices.com/CloudFormationSchema/CloudFormationV1.schema)

Which seems like exactly that, a JSON schema.

My questions is two fold, is this a well maintained and generally up-to-date schema for the resources in CF?

If so would you mind if I added it as a dependency to cfndsl (I'll work out the best way of using it + caching etc) as this would really help with the ongoing maintenance of the project and help keep it as up-to-date as possible.

Steve

**Comment by ebekker** [comment]
Please see https://github.com/stevenjack/cfndsl/issues/264
