### ISSUE TITLE
aws toolkit is not getting installed in Version: 2019-03 (4.11.0) eclipse

### ISSUE THREAD

**Issue by abhilashatmobile** [aws/aws-toolkit-eclipse#144]
Cannot complete the install because one or more required items could not be found.
Software currently installed: Amazon RDS Management 1.0.0.v201807201743 (com.amazonaws.eclipse.rds.feature.feature.group 1.0.0.v201807201743)
Missing requirement: Amazon Relational Database Service (RDS) Plugin 1.0.0.v201807201743 (com.amazonaws.eclipse.rds 1.0.0.v201807201743) requires 'osgi.bundle; org.eclipse.datatools.connectivity.ui.dse 1.1.0' but it could not be found
Cannot satisfy dependency:
From: Amazon RDS Management 1.0.0.v201807201743 (com.amazonaws.eclipse.rds.feature.feature.group 1.0.0.v201807201743)
To: org.eclipse.equinox.p2.iu; com.amazonaws.eclipse.rds [1.0.0.v201807201743,1.0.0.v201807201743]
OK
![image](https://user-images.githubusercontent.com/49854880/56663558-03823980-66c4-11e9-9691-eb1a12fefa86.png)

**Comment by zhangzhx** [comment]
The RDS plugin depends on [DataTools](org.eclipse.datatools.connectivity.ui.dse) plugin. I'm wondering which release of Eclipse you are installing? The [Eclipse EE](https://www.eclipse.org/downloads/packages/release/kepler/sr2/eclipse-ide-java-ee-developers) by default includes DataTools so that you don't need to install them separately. If the release doesn't have this plugin installed, you need to install this first.

**Comment by asweeney99** [comment]
I have Eclipse IDE for Java Developers. Version: 2019-03 (4.11.0) Build id: 20190314-1200. My AWS toolkit has completely disappeared from eclipse. No icon. No AWS option in any context menu. It was working perfectly before now. It seems as if some update has completely deleted the AWS toolkit.

**Comment by asweeney99** [comment]
I was able to resolve this issue by just following the install instructions here:

[https://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/setup-install.html](url)

There was no need to re-configure my AWS credentials. The re-install procedure seemed to find them and my sother AWS settings without a problem. I was able to upload my Lambda function in the usual way.

**Comment by abhilashatmobile** [comment]
Thanks Everyone!!
I was able to resolve the issue by following the steps mentioned in https://aws.amazon.com/eclipse/
