### ISSUE TITLE
[ERROR] Cannot resolve project dependencies:

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-toolkit-eclipse#145]
I was installing AWS Toolkit for Eclipse. When I got to the step in the instructions to run setup.sh, I received the following error messages in terminal:

[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.amazonaws.eclipse.devide raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: com.amazonaws.eclipse.devide raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT requires 'org.eclipse.jst.web_sdk.feature.feature.group 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: com.amazonaws.eclipse:com.amazonaws.eclipse.devide:1.0.0-SNAPSHOT @ /Users/shinehah/git/aws-toolkit-eclipse-java-ee-and-report/releng/com.amazonaws.eclipse.devide/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

The URL given in the last message does not work.

How do I fix this?

The solution to Issue #46 doesn't help much because I haven't created a project yet.

**Comment by Shinehah-Gnolaum** [comment]
It looks like I'm missing a jar file for org.eclipse.jst.web_sdk.feature.feature.group. I am not able to find a download for that anywhere.

**Comment by zhangzhx** [comment]
What Eclipse distribution are you using? It seems in your distribution, you don't have [WebTools](https://www.eclipse.org/webtools/) installed which is a dependency for the toolkit. Can you install that first? Also, we recommend to use Eclipse EE distribution as that bundled the WebTools plugin.

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx I am using the Eclipse EE and Report.

**Comment by Shinehah-Gnolaum** [comment]
I might have made a mistake in using Gradle to install Maven. I think I was able to successfully reinstall Maven over the installation that was using Gradle. What if I uninstall it all and start over? Is that a solution?

**Comment by zhangzhx** [comment]
Sorry I was not following you. Why are you using Gradle to install Maven? Are you trying to install the Toolkit? You can install the Toolkit for following [the instructions](https://aws.amazon.com/eclipse/) in the top right.

**Comment by Shinehah-Gnolaum** [comment]
I used Gradle because I ran into a problem installing Maven the other way.

**Comment by Shinehah-Gnolaum** [comment]
I have both Eclipse for Java and Eclipse for Java EE on my macOS. I was able to use AWS Java SDK v1 on Eclipse for Java. The problem I was having was with Eclipse for Java EE. I am running into another problem with Eclipse for Java. I don't think it had Web Tools on it when I installed AWS Java SCK v1. Would it work if I install Web Tools now, or would I have to uninstall AWS Java SDK v1 first.

**Comment by Shinehah-Gnolaum** [comment]
How do I check if I have Web Tools installed on Eclipse for Java?

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx The instructions you give me generate an error message saying that required items cannot be found and the following details:

Cannot complete the install because one or more required items could not be found.
Software currently installed: AWS CodeStar Plugin 1.0.0.v201807201743 (com.amazonaws.eclipse.codestar.feature.feature.group 1.0.0.v201807201743)
Missing requirement: AWS CodeStar Plugin 1.0.0.v201807201743 (com.amazonaws.eclipse.codestar 1.0.0.v201807201743) requires 'osgi.bundle; org.eclipse.m2e.core 1.5.1' but it could not be found
Cannot satisfy dependency:
From: AWS CodeStar Plugin 1.0.0.v201807201743 (com.amazonaws.eclipse.codestar.feature.feature.group 1.0.0.v201807201743)
To: org.eclipse.equinox.p2.iu; com.amazonaws.eclipse.codestar [1.0.0.v201807201743,1.0.0.v201807201743]

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx Which version of Web Tools should I use, the one for Users, Adopters, or Commiters?

**Comment by Shinehah-Gnolaum** [comment]
It looks like I got a working copy of Eclipse for Java with AWS Toolkit by using regular Eclipse for Java (not EE) and installing Web Tools then installing AWS Toolkit.

**Comment by zhangzhx** [comment]
If you use Eclipse EE edition, you should have Web Tools builtin. See my attached screenshot for how to install Eclipse EE with the Eclipse installer. Here are the description about [Eclipse EE built-in features](https://www.eclipse.org/downloads/packages/release/2018-12/r/eclipse-ide-enterprise-java-developers).

<img width="556" alt="Screen Shot 2019-06-04 at 9 34 56 AM" src="https://user-images.githubusercontent.com/7167513/58896981-19642080-86ac-11e9-9ecf-a4fae0d6f6e3.png">

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx Ok. I got it. I was confused by which one was Eclipse Java EE. Stupid mistake. I understand now. Thank you for showing that screenshot.
