### ISSUE TITLE
Do I have to install aws/aws-sdk-java-v2 from GitHub before I install aws/aws-toolkit-eclipse?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-toolkit-eclipse#147]
Do I have to install https://github.com/aws/aws-sdk-java-v2 from GitHub before I install aws/aws-toolkit-eclipse if I want to use aws-sdk-java-v2, or does aws-toolkit-eclipse already include aws-sdk-java-v2? I have an instance of Eclipse that doesn't have the EC2 option in one of the wizards, I forget which, so I thought it was because I don't have aws-sdk-java-v2 installed.

**Comment by zhangzhx** [comment]
No you don't have to. You can simply add aws-sdk-java-v2 as a dependency in your gradle/maven build system. It is not related to the toolkit.

For installing the AWS Toolkit, you can simply follow the [instructions here](https://aws.amazon.com/eclipse/) on the top right. You don't have to checkout this repository.

**Comment by Shinehah-Gnolaum** [comment]
Ok. Thank you. I am getting errors whichever ways I've been trying.
