### ISSUE TITLE
Which instructions do I follow in the documentation for aws/aws-toolkit-eclipse?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-toolkit-eclipse#148]
When I install was-toolkit-eclipse on an existing eclipse, could I just jump to this step: https://github.com/aws/aws-toolkit-eclipse#import-into-eclipse-and-set-up-development-environment titled "Import into Eclipse and Set up Development Environment", or do I have to do "Build and Test with Maven"?

How do I know which version of Eclipse I am using? The About Eclipse dialog box doesn't give the nickname, just the version number and build number.

**Comment by zhangzhx** [comment]
You can follow the [documentation](https://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/welcome.html) here for how to install and use the AWS Toolkit for Eclipse. You don't have to check out the source code here for installing the toolkit.

**Comment by Shinehah-Gnolaum** [comment]
Ok. Thank you.
