### ISSUE TITLE
Error updating AWS Elastic Beanstalk environment - javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-toolkit-eclipse#149]
I'm using the latest Eclipse IDE for Java Developers, Version: 2019-03 (4.11.0), Build id: 20190314-1200, with Java 12.0.1.

When I try to start a server to run my aws web project in Eclipse with AWS Toolkit, I get an error message in a dialog box:

'Updating AWS Elastic Beanstalk environment: TrialEnvironment02' has encountered a problem.

An internal error occurred during: "Updating AWS Elastic Beanstalk environment: TrialEnvironment02".
  javax/xml/bind/JAXBException

The server starts and then stops, but the web project continues to say starting.

How do I go about fixing this?

I read in some sources that I need to alter one of the xml files, but I'm not sure where to look for those xml files.

It would help if I knew how I could find out which directories Java SDK or AWS SDK or AWS Toolkit are in. How would I find that out. My experience is very limited.

**Comment by zhangzhx** [comment]
The Eclipse Toolkit doesn't support Java 12 at the moment. Can you switch back to use Java 8 instead? We have a similar issue at #123. Please track that instead.

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx Ok. I'll try to do that.

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx I switched from Java 12 to Java 8 like you suggested, and now I get a different error:

An internal error occurred during: "Updating AWS Elastic Beanstalk environment: TrialEnvironment08".
javax/xml/bind/JAXBException

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx I'll open another issue for this.

**Comment by Shinehah-Gnolaum** [comment]
I'm still getting that error.

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx I just noticed that the JRE System Library node of my web project says Java SE 12.0.1. I had uninstalled 12 and installed 8. Why does it say that?

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx When I go to Properties for JRE System Library by right-clicking the JRE System Library node of my project in Project Explorer, and click on the Installed JREs button, when I selcect Java 8, I get a warning at the top of the dialog box that says "The selected JRE does not support...t compiler compliance level of 11".

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx The Java Resources node of the web project has an error icon on it (red box with an x in the middle), but none of the nodes under that have an error icon on it. Am I missing something I should put in the Java Resources node?

**Comment by zhangzhx** [comment]
@Shinehah-Gnolaum, is this project your personal project or created by AWS Toolkit for Eclipse? Can you show me the screenshot for the error? It seems your project has set the language level to Java 11.

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx My project is an AWS Java Web App Project. I had uninstalled Java 12 and installed Java 8. Also, I set Java JRE node to Java 8, but when I set the Properties->Project Facets to check Dynamic Web Module, once I press on apply, the Project shows a JRE node saying JavaScript instead of showing the JRE node, and the Maven node also disappears.

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx Let me find a way to show you a screenshot. I'll let you know.

**Comment by Shinehah-Gnolaum** [comment]
Here is a link to my screenshot of my eclipse trial web projects:

https://1drv.ms/u/s!AooJiM96YK-_7hRqtUJOrRhNpDl7

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx 

Here is the screenshot of the error message:

https://1drv.ms/u/s!AooJiM96YK-_7hYBwTErMcJ_19q6

Here is a screenshot of my webproject:

https://1drv.ms/u/s!AooJiM96YK-_7hRqtUJOrRhNpDl7

Here is a screenshot of the server view:

https://1drv.ms/u/s!AooJiM96YK-_7hUopp5hyup1pNw-

**Comment by Shinehah-Gnolaum** [comment]
@zhangzhx Have you come to any conclusions about this issue? I was able to get this to work on my PC, but I would like to get this to work on my Mac.

**Comment by Shinehah-Gnolaum** [comment]
I checked the Java version, and for some reason it was still using version 12. I changed to version 8 and the problem went away.

**Comment by malikze** [comment]
@Shinehah-Gnolaum I am also facing this issue at the moment. Could you please explain in more detail how you managed to solve it (step by step if possible)?
Thanks.

**Comment by Shinehah-Gnolaum** [comment]
@malikze That was a long time ago. I don't even remember the problem.
