### ISSUE TITLE
What third party dependencies do I need to install?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-toolkit-eclipse#153]
Under this heading [https://github.com/aws/aws-toolkit-eclipse#build-and-test-with-maven](url) titled "Build and Test with Maven" in your documentation, at step 3, which says "Install the third-party dependencies and build the target platform: sh setup.sh", what are the third party dependencies?

**Comment by justinmk3** [comment]
`setup.sh` installs the dependencies, which are defined in the pom.xml
