### ISSUE TITLE
I didnt run this code, because Failed to launch SAM local

### ISSUE THREAD

**Issue by Anwar45** [aws/aws-toolkit-eclipse#162]
ublic class ManagementStaff {
	
	//access level of the class using an access modifier.
	//access modifier are like gate keepers, they control who has access to that class.
	
	//public means the class can be accessed by any class in the program.
	// contents of class include constructors, fields, methods, interfaces, and other classes.
	
	//Fields
	
	//we will first declare the fields for our Staff class. 
	
	private String nameOfStaff;
	private final int hourlyRate=30;
	private int hoursWorked;
	
	//we can declare a field either private, public or protected. 
	private final int hoursRate=30;
	
	//Methods
	
	public void printMessage()
	{
		System.out.println("Calculating Pay...");
	}
	/*This method is declared as
	 *  public void pringMessage() 
	 * { 
	 * };
	*/
	public int calculatePay()
	{
		printMessage();
		
		int staffPay;
		staffPay=hoursWorked*hourlyRate;
		
		if(hoursWorked>0)
			return staffPay;
		else
			return -1;
		
		 /* this method is declared as
        * public int calculatePay()
        * {
        * };
        */
          
		 // OverLoading
	}
	
	 public int calculatePay(int bonus, int allowance)
	    {
	    	printMessage();
	    	if (hoursWorked>0)
	    		return hoursWorked*hourlyRate+bonus+allowance;
	    	else
	    		return 0;
	    	/*
	    	 * The signature of the first method is calculatePay() 
	    	 * while that of the second method is calculatedPay(int bonus, int allowance).
	    	 */
	    }
	 
	 // Getter and Setter Methods
	 
	 public void setHoursWorked(int hours)
	 {
		 if(hours>0)
			 hoursWorked=hours;
		 else
		 {
			 System.out.println("Error: HoursWorked cannot be smaller than zero");
			 System.out.println("Error: HoursWorked is not updated");		 
		 }
	 }
	 public int getHoursWorked()
	 {
		 return hoursWorked;
	 }
}

**Comment by jalvarezferr** [comment]
Can you please be more specific about the issue you suffer in lauching SAM local? Your code is just a plain POJO class that has nothing to do wit AWS or Eclipse if you don't provide a SAM file or something that links it to them.
