### ISSUE TITLE
Unresolved dependencies prevent install in Eclipse  2018-09 (4.9.0)

### ISSUE THREAD

**Issue by FLATT-Dev** [aws/aws-toolkit-eclipse#169]
Install of the required items fails with the error below
Tried installing from aws site and from  https://aws.amazon.com/eclipse the jar file downloaded from  github
TIA
--------------------------------------------------
Cannot complete the install because one or more required items could not be found.
Software currently installed: AWS CloudFormation Tools 1.0.0.v201807201743 (com.amazonaws.eclipse.cloudformation.feature.feature.group 1.0.0.v201807201743)
Missing requirement: AWS Toolkit Core Plugin 2.3.1.v201807201743 (com.amazonaws.eclipse.core 2.3.1.v201807201743) requires 'osgi.bundle; org.eclipse.m2e.core 1.5.1' but it could not be found
Cannot satisfy dependency:
From: AWS CloudFormation Tools 1.0.0.v201807201743 (com.amazonaws.eclipse.cloudformation.feature.feature.group 1.0.0.v201807201743)
To: org.eclipse.equinox.p2.iu; com.amazonaws.eclipse.core 2.0.1

**Comment by rli** [comment]
Hi, this looks like https://github.com/aws/aws-toolkit-eclipse/issues/109.

Please make sure your version Eclipse has Maven support. The "Eclipse IDE for Java Developers" package should come with this by default.

**Comment by FLATT-Dev** [comment]
Thank you. I installed the latest Eclipse and it worked
Andy
