### ISSUE TITLE
error while trying to create a new aws java project in eclipse

### ISSUE THREAD

**Issue by saiakhil717** [aws/aws-toolkit-eclipse#172]
Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6
Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6
Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6

**Comment by justinmk3** [comment]
what version of java?

**Comment by saiakhil717** [comment]
Thanks @justinmk3 ,but the error solved when I deleted the plugin and updated the maven project-force update
