### ISSUE TITLE
 The server does not support version 3.1 of the J2EE Web module specification.

### ISSUE THREAD

**Issue by bebud** [aws/aws-toolkit-eclipse#18]
with tomcat 8 on aws it is not possible to deploy a java 8 web app using 3.1 web module facet.

Steps:
latest Springsource Tool Suite. Install AWS toolkit. create simple spring starter project with web module using java 1.8 and packaging war. 
try to add to Elastic Beanstalk tomcat 8.

works on local tomcat 8 Server.

**Comment by kennyk65** [comment]
I've encountered the same.  Message is "The server does not support version 3.1 of the J2EE Web module specification."

 To add, if I build a war and upload via AWS management console, the app runs without incident.  Elastic beanstalk runs Tomcat 8 with Java 8.  Note really sure what Eclipse means by "J2EE Web Module Specification", I assume they mean "JEE Servlet Specification"

**Comment by fulghum** [comment]
Thanks for reporting this issue.  It looks like we need to update our server configuration in the plugin to support version 3.1 of Eclipse WTP web modules.  We'll test out this change and see if we can get it out in our next release.

**Comment by hanshuo-aws** [comment]
@bebud @kennyk65 This should be fixed in the latest v2.7.1 release. Please upgrade the AWS plugins to the latest and let us know how it works out.
