### ISSUE TITLE
AWS CloudFormation Editor for Eclipse appears not to work

### ISSUE THREAD

**Issue by henrjk** [aws/aws-toolkit-eclipse#19]
I am aiming to get started with CloudFormation and a good editor should help a lot in learning CF and in writing this efficiently. I have used Eclipse before and was expecting capabilities perhaps akin to the JDT editors  in the CloudFormation Template Editor. 

Assuming that AWS Toolkit for Eclipse and Visual Studio are providing similar features the following video shows the kind of capabilities I was looking for: _AWS Toolkit for Microsoft Visual Studio_  at https://www.youtube.com/watch?v=3QydWLiCqWk 

Also I briefly looked into source code of the eclipse editor plugin as well as found a schema mentioned which appears to indicate that this should work much better. 

I installed the OS X version of Eclipse recommend at http://docs.aws.amazon.com/AWSToolkitEclipse/latest/GettingStartedGuide/tke_setup_prereqs.html (`eclipse-jee-kepler-R-macosx-cocoa-x86_64.tar.gz`) and I am running this on OS X 10.9.5. However I am also seeing this on a Windows 7 machine. 

I can open the editor on a file called `cloudformer.template.json` with context Menu then Open With/Other.. and then select  'Amazon CloudFormation Template Editior'. The Editor appears to open fine and I can edit as if in a basic JSON editor as expected.

However I do not get see much additional assistance. For example when introducing errors such as changing `"true"` to `"tr sd ue"`. 
Content assist appears to react only for:
- The Type Value
- At the top level suggesting Conditions, Mappings, Outputs, and Parameters. When I select Conditions it actually merges the value with the AWSTemplateFormatVersion value leading to a syntax error.

I'd be happy to provide more details as needed.

**Comment by fulghum** [comment]
Hey Henrich, sorry for the slow response on this one.  The functionality between Visual Studio and Eclipse is a little different, but the major features should be fairly comparable.  If you can give us some more specific cases where the editor isn't working as you'd expect, then we can repro and prioritize the fix.  The example about changing "true" to "tr sd ue" is a good one we can start with.

**Comment by henrjk** [comment]
When I enter CTRL-CMD here https://gist.github.com/henrjk/ced5e3a46dc3d9c015cd#file-cloudformer-template-json-L3 I get the https://gist.github.com/henrjk/ced5e3a46dc3d9c015cd#file-eclipse-error.

Here to repeat 
```
Caused by: java.lang.NullPointerException
	at com.amazonaws.eclipse.cloudformation.templates.editor.TemplateContentAssistProcessor.provideRootLevelAutoCompletions(TemplateContentAssistProcessor.java:308)
	at com.amazonaws.eclipse.cloudformation.templates.editor.TemplateContentAssistProcessor.computeCompletionProposals(TemplateContentAssistProcessor.java:361)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1839)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:566)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:563)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$14.run(CompletionProposalPopup.java:1569)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.incrementalComplete(CompletionProposalPopup.java:1563)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1664)
```

I have not seen this particular exception before.

**Comment by henrjk** [comment]
After renaming file `cloudformer.template.json` to `cloudformer.template.json` I see a proper icon. See screenshot:

![screen shot 2015-06-17 at 19 22 42](https://cloud.githubusercontent.com/assets/7439282/8213974/511bfa44-1526-11e5-9361-21e3c8cfae8b.png)

Now content assist on the top level appears OK but when selecting *Conditions* an error is introduced as shown in the screenshot.

**Comment by henrjk** [comment]
On the previous comment when I try CTRL+CMD on inside the existing `"Properties"` of `vpc3d2adc54` I do not get content assists, only beeps. There are no new errors in the 'Error Log' either. 
Also I don't see tooltips either when hovering anywhere. 

The only place beyond the one mentioned in previous comment I managed to get content assist is with CTRL+CMD inside `"AWS::EC2::VPC"`. This works pretty well as the list of choices changes depending on where the cursor is and there is also help text.

![screen shot 2015-06-17 at 19 32 55](https://cloud.githubusercontent.com/assets/7439282/8214187/b8932a16-1527-11e5-82a3-b3bf3e1741cb.png)

If I introduce syntactical JSON errors I see problem markers in the editor and error squiggles:
![screen shot 2015-06-17 at 19 35 45](https://cloud.githubusercontent.com/assets/7439282/8214244/3ab6ce44-1528-11e5-8499-d8625475fa18.png)
However the Problems View remains empty. Perhaps this is expected.

While typing in a new property no content assist is available nor or is nonsensical content marked as errors (see Foo World):
![screen shot 2015-06-17 at 19 39 05](https://cloud.githubusercontent.com/assets/7439282/8214296/8e18428e-1528-11e5-8dbb-8ad1adf7cc1c.png)

**Comment by zhangzhx** [comment]
We had just released an enhancement version of the CloudFormation editor in Eclipse [v201707121824](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201707121824).

Feel free to try this out and let us know what further features you want us to add to the editor. We'd glad to hear your feedback.
