### ISSUE TITLE
Unsupported solution stack: 64bit Amazon Linux 2 v3.0.0 running Corretto 11

### ISSUE THREAD

**Issue by yatendragoel** [aws/aws-toolkit-eclipse#190]
### IDE: 
Spring Tool Suite 

Version: 3.9.6.RELEASE
Build Id: 201809180749
Platform: Eclipse 2018-09 (4.9.0)

### Issue:
When I click on "AWS Elastic Beanstalk" > App > Environment > right-click > "open in WTP Server Editor", I get the following error message:

> Unable to open the server editor: Unsupported solution stack: 64bit Amazon Linux 2 v3.0.0 running Corretto 11
Unsupported solution stack: 64bit Amazon Linux 2 v3.0.0 running Corretto 11

<img width="670" alt="Screenshot 2020-05-06 at 20 04 10" src="https://user-images.githubusercontent.com/1221759/81190463-81666980-8fd5-11ea-9dba-3d8683432eaf.png">

**Comment by kiiadi** [comment]
Unfortunately the Eclipse toolkit doesn't support Java11 at this time - we have an open tracking issue for this : https://github.com/aws/aws-toolkit-eclipse/issues/171

**Comment by DivyaD2805** [comment]
It this issue fixed ?
