### ISSUE TITLE
Python support Lambda

### ISSUE THREAD

**Issue by edwardsa829** [aws/aws-toolkit-eclipse#206]
Does AWS eclipse toolkit support python language for Lambda??

**Comment by awschristou** [comment]
Hello, the Eclipse Toolkit does not support Python Lambda functions.
You might be interested in trying out our [AWS Toolkit for JetBrains](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/welcome.html), which allows you to develop, debug, and deploy Python Lambda Functions in IDEs like PyCharm.
