### ISSUE TITLE
Uploading Lambda function failed in Eclipse 2020-12 (4.18.0)

### ISSUE THREAD

**Issue by anandlalvb-rvs** [aws/aws-toolkit-eclipse#222]
I am using Eclipse Version: 2020-12 (4.18.0) Build id: 20201210-1552. 

Uploading lambda function is failing with below error

An internal error occurred during: "Uploading function code to Lambda".
javax/xml/bind/JAXBException

<img width="402" alt="Screen Shot 2021-01-05 at 3 34 23 PM" src="https://user-images.githubusercontent.com/17467079/103633355-a26bc980-4f6b-11eb-9d8b-887e47097ff9.png">

**Comment by sbuggan** [comment]
Could someone share are these any solutions found out for this problem?

**Comment by eschulma** [comment]
Later versions of Eclipse use the Java 11 runtime, which removed this class among many others, and the plug is running a very old version of the Java SDK. I have opened a pull request which I hope gets approved, in the meantime, you would need to use an older version of Eclipse instead. The 2019 ones use Java 8.

**Comment by kiiadi** [comment]
currently the eclipse toolkit is not compiled for Java11 - there's a tracking issue open for this : https://github.com/aws/aws-toolkit-eclipse/issues/171
