### ISSUE TITLE
provide support for AWS codecommit

### ISSUE THREAD

**Issue by javamonkey79** [aws/aws-toolkit-eclipse#23]
Because Eclipse uses JGIT for git integration, eGit does not work with AWS codecommmit in most places. I've opened a bugzilla ticket for the JGIT team here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=472415, but they (nor I) have expertise with AWS IAM auth.

**Comment by fulghum** [comment]
Hey Shaun, have you been able to get eGit working with CodeCommit by using SSH authentication?  That might be an easier path than a custom jGit authentication for AWS signing:
http://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-credentials-ssh.html

**Comment by javamonkey79** [comment]
Great idea! I didn't know this was possible but will try it out.

**Comment by fulghum** [comment]
No problem.  Let us know if you hit any snags.  The SSH authentication feature is likely the easiest way to get CodeCommit to integrate with other tools.  Let us know how it works and if there was anything along the way (like the key pair setup) that we could make easier for developers.

**Comment by SonyDavid** [comment]
Hi,

I'm behind a company firewall and ssh isn't an option. Any chance this can be looks at some more.

David

**Comment by zhangzhx** [comment]
Hi, we have launched the AWS CodeCommit plugin for Eclipse together with the new service AWS CodeStar. Please see this [blog post](https://aws.amazon.com/blogs/developer/aws-toolkit-for-eclipse-support-for-aws-codecommit-and-aws-codestar/) for more information how to use these two plugins. Recently, AWS IAM launched a new feature to [configure Git credentials for AWS CodeCommit](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_ssh-keys.html#git-credentials-code-commit). It extremely simplifies the process to connect AWS CodeCommit repo.

Welcome to try this new feature and let us know what you think about it.
