### ISSUE TITLE
Excessively vague error: "Unable to connect"

### ISSUE THREAD

**Issue by minfrin** [aws/aws-toolkit-eclipse#24]
From a brand new clean Eclipse Mars installation, along with a brand new clean AWS installation, when an attempt is made to configure credentials for the first time, all tabs result in an object being displayed called "Unable to connect".

This object has no context sensitive help, and doesn't respond to being double clicked. Without a reason given for "unable to connect" the end user is left guessing.

(After some googling for a while I stumbled on someone claiming that this was a permissions problem. Allocating "administrator" permissions allowed further progress, however users should not have to resort to google-archeology to get the job done).

**Comment by zhangzhx** [comment]
Closing this issue since we don't have plan to fix this. Feel free to reopen it if you still have more questions.
