### ISSUE TITLE
CloudFormation template 'Run on AWS' -> Update Stack remembers all previous stack names.

### ISSUE THREAD

**Issue by maitreya1975** [aws/aws-toolkit-eclipse#26]
When deploying a CloudFormation template using the 'Run on AWS' -> Update Stack menu item, the list of stacks that is populated in the drop down includes all stacks past and present. The list keeps growing even if the corresponding stacks have been deleted in CloudFormation.
This makes it confusing to find the exact name of the stack that needs to be updated.
It would be better to query CloudFormation for the current list of Created stacks that can be selected for Update.

**Comment by Benvandamme** [comment]
Same Problem here. But also a often used Stackname disappeared and is not selectable anymore.

**Comment by zhangzhx** [comment]
This was fixed in the latest release. Sorry for the slow update.
