### ISSUE TITLE
Update CloudFormation Stack requires you to change the value of the paramters before proceeding.

### ISSUE THREAD

**Issue by maitreya1975** [aws/aws-toolkit-eclipse#27]
The second menu in the Update CloudFormation Stack wizard shows the values of the parameters but you have to edit at least one value to proceed. If I want to keep the parameter values the same as before, I'm forced to edit the text field and make a change and revert it before I can move to the next step.
Please make it optional to edit the values of the parameters - there are many cases where the template is being updated but the parameters stay unchanged.

**Comment by zhangzhx** [comment]
Do you still see this issue? Please try our latest version release [v201707121824](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201707121824) and let us know if you still see this issue.
