### ISSUE TITLE
Elastic Based Storage List - Enhancement

### ISSUE THREAD

**Issue by waynetaylor** [aws/aws-toolkit-eclipse#28]
In Spring Tool Suite/Eclipse, when i got to EBS Storage. It returns a long list and IDE takes some time to resolve. The list returns all snapshots of the EBS, including those created much earlier than the EBS Volume ID.

Example volume, vol-ea260cad created on May 2nd 2015 has snapshots going back to 2008, snapshot ID: snap-d010f6b9. Enhancement would to only show snapshots greater than EBS creation date by default. 

![image](https://cloud.githubusercontent.com/assets/2912112/10582480/bbc99bc0-764d-11e5-8f63-0e1ef6d3e33a.png)

**Comment by zhangzhx** [comment]
Closing this issue since we don't have plan to fix it for now. Feel free to reopen it if you still have more questions.
