### ISSUE TITLE
CloudFormation Editor: Better error reporting and bracket matching.

### ISSUE THREAD

**Issue by maitreya1975** [aws/aws-toolkit-eclipse#32]
The CloudFormation Editor could be improved with better error reporting and bracket matching.

Right now, if you make a single mistake in the JSON text an error highlight appears but it is not usually close to where the error happened.

The most common types of errors are mismatched brackets - it would be great for the editor to automatically highlight the corresponding brackets when hovering over it or moving the cursor to a bracket.

The feature of formatting the template does not help if the template is not valid JSON - this would be a great way to detect basic errors of extra commas or mismatched brackets.

JSON editing is a pain and anything you can do to improve this would be a great help.

**Comment by zhangzhx** [comment]
We just released an enhanced version of the CloudFormation editor in release [v201707121824](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201707121824). Feel free to try this out and let us know what you think.
