### ISSUE TITLE
AWS Java Project copies AWS API credentials into a property file in the deployment.

### ISSUE THREAD

**Issue by maitreya1975** [aws/aws-toolkit-eclipse#33]
I used the Create new AWS Java Project wizard to create a sample Java project and deploy it to ElasticBeanstalk (EB). I noticed that it automatically copied my AWS credentials and placed them in the clear in a property file that was bundled and uploaded to EB.
The sample app then uses the credentials to query EC2 instances, S3 buckets and DyanmoDB tables.
This is not recommended as EC2 Instance Profiles should be used instead to grant these specific permissions.

**Comment by fulghum** [comment]
Hey Maitreya, thanks for opening this issue.  You're absolutely correct that the Toolkit isn't starting you off with the best-practice for handling security credentials.  EC2 Instance Profiles are a great feature and solve the credential distribution problem very cleanly.  

We'll take a look at updating the AWS Java Web Project templates in the Eclipse Toolkit on our next sprint and see how we can get these cleaned up.

**Comment by zhangzhx** [comment]
Hello Maitreya, we just released a new update for Elastic Beanstalk **AWS Elastic Beanstalk	1.0.0.v201603240955**. In this new update, the sample project will not copy the credential, instead it will use the EC2 Instance Profiles when run remotely, and load the profile you provided when creating this sample project directly from the default credential file **~/.aws/credentials**.

I'm closing this issue, and feel free to reopen it if you have further questions.
