### ISSUE TITLE
AWS Toolkit for Eclipse bug: Mars

### ISSUE THREAD

**Issue by alartin** [aws/aws-toolkit-eclipse#37]
Hi all,
I've used the default and latest version of Eclipse: Mars and installed AWS Toolkit. But when I try to create a new AWS java project, it can not find the AWS java sdk at all. I am sure it is in the installed software list. I guess it might be an incompatible issue of the Mars version.  Could anybody help? Thanks!

**Comment by zhangzhx** [comment]
Hello @alartin ,

Thanks for reaching out to us. It could be the incompatibility problem. Have you tried using Luna version of Eclipse?

Could you provide us with the error log? And what is the version of AWS Toolkit for Eclipse you installed?

**Comment by zhangzhx** [comment]
Do you still see the problem @alartin? Don't hesitate to reopen it if you still have more questions.
