### ISSUE TITLE
CloudFormation schema correction

### ISSUE THREAD

**Issue by ebekker** [aws/aws-toolkit-eclipse#38]
There seems to be a bug in the CloudFormation schema file at [CloudFormationV1.schema](http://vstoolkit.amazonwebservices.com/CloudFormationSchema/CloudFormationV1.schema) for resource `AWS::EC2::VPC` property `InstanceTenancy` which is described with a type of `Number` but lists strings for its `allowed-values` -- here's the snippet:

``` JSON
          "InstanceTenancy": {
            "type": "Number",
            "allowed-values": [
              "default",
              "dedicated"
            ],
            "required": false,
            "description": "The allowed tenancy of instances launched into the VPC. A value of \"default\" means instances can be launched with any tenancy; a value of \"dedicated\" means instances must be launched with tenancy as dedicated."
          },
```

I'm submitting this ticket here, although I'm not sure it's the correct forum.  I know that there has been some other discussion related to the schema file in #14.

If this is the not the correct mechanism to submit requests related to the CFN schema file, please advise.

**Comment by ebekker** [comment]
Incidentally, the [User Guide description](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html) of this resource, lists this property as `String` type so it looks like this is just a mix up in the schema file.

**Comment by ebekker** [comment]
Found another deviation for the resource `AWS::EC2::Route` as described [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html).  The schema is missing a property `NatGatewayId` which allows you to add a route to a NAT Gateway resource.  Without this property, you can't route to a NAT Gateway using CloudFormation templates.

**Comment by zhangzhx** [comment]
This has been corrected. Thanks for reporting this issue.
