### ISSUE TITLE
Support for RequestStreamHandler within Lambda Java Projects

### ISSUE THREAD

**Issue by parkej60** [aws/aws-toolkit-eclipse#39]
It appears as if this plug-in doesn't support Lambda functions that implement the RequestStreamHandler interface. I'm trying to upload them via the 'Upload function to Lamba' option from within Eclipse and it presents me with the following error.

https://cloudup.com/cCMd-BarFLP

**Comment by bbilger** [comment]
FYI, there's a workaround: implement RequestHandler and upload the function, then implement RequestStreamHandler, instead and use "Run function on AWS Lambda..." instead of "Upload function to AWS Lambda" which uploads the updated function.

**Comment by parkej60** [comment]
Thanks for the heads up on that. Will this work for functions that already exist?

Jameson W Parker

**Comment by bbilger** [comment]
Well, it's really just a workaround I found. It should work, yes but by implementing RequestHandler instead of RequestStreamHandler and uploading, you'll overwrite your existing function and potentially break what the function is intended to do.

**Comment by parkej60** [comment]
Well right now they already use request stream handler. They've just been upload via the web ui instead of eclipse. They actually extend a class which extends RequestStreamHandler.

Jameson W Parker

**Comment by zhangzhx** [comment]
Hi @parkej60 ,

In our latest release, we started supporting RequestStreamHandler. Please try the newest version of the Lambda plugin and we would like to hear your feedbacks for the new feature.

**Comment by parkej60** [comment]
@zhangzhx IT WORKS! Thank you so much this makes Lambda functions so much better!
