### ISSUE TITLE
[Improvement] Can't copy keys from DynamoDB / SimpleDB views

### ISSUE THREAD

**Issue by itoshkov** [aws/aws-toolkit-eclipse#4]
There seems to be no way to select and copy a key from DynamoDB or SimpleDB view. The editable elements can be selected and copied, but not the keys. This is quite frustrating, as keys tend to be UUIDs or other generated and hard to retype correctly strings.

Please add a way to copy the keys to the clipboard.

**Comment by zhangzhx** [comment]
Resolving this for the long time spanning. If you still need this feature, please cut a new issue. Thank you.
