### ISSUE TITLE
timeout of only up until 60 secs can be entered for lambda function when real max is 300 secs

### ISSUE THREAD

**Issue by simonnishi** [aws/aws-toolkit-eclipse#41]
When following the steps to upload a lambda function to AWS, the timeout value under Advanced Settings can only be set to 60 secs but in fact it can be set to up to 5 mins (300 secs) through the AWS Lambda Console on the web.

It looks like the code is that needs to be set to 300 is:

com.amazonaws.eclipse.lambda/src/com/amazonaws/eclipse/lambda/upload/wizard/page/FunctionConfigurationComposite.java 
94	    private static final int MAX_TIMEOUT = 60;

**Comment by zhangzhx** [comment]
Closing this issue as this change has been released:

https://github.com/aws/aws-toolkit-eclipse/blob/master/com.amazonaws.eclipse.lambda/src/com/amazonaws/eclipse/lambda/upload/wizard/page/FunctionConfigurationComposite.java#L94
