### ISSUE TITLE
org.eclipse.ui.startup

### ISSUE THREAD

**Issue by dylantuttle** [aws/aws-toolkit-eclipse#42]
Hello,

The following message came up when I tried opening an Elastic Beanstalk environment:

``!ENTRY org.eclipse.ui 2 0 2016-04-12 16:27:56.298
!MESSAGE The 'org.eclipse.ui.startup' extension from 'com.amazonaws.eclipse.elasticbeanstalk' does not provide a 'class' attribute.
This usage is deprecated and a 'class' attribute should be provided.
The release after Mars (4.5) will no longer support the deprecated usage!``

I am running Eclipse 4.5 (Mars) Java EE with openjdk-7-jdk. Should I try Luna?

Thanks,
Dylan

**Comment by zhangzhx** [comment]
Weird! I am using Mars and not seeing this error message. Do you still see this error message on Luna?

**Comment by dylantuttle** [comment]
No, I don't see this error message in Luna, but I am still not able to view my Elastic Beanstalk environments. I am able to view my EC2 Instances. Here is the log:

```
!SESSION 2016-04-14 11:18:42.674 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_95
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY com.amazonaws.eclipse.core 1 0 2016-04-14 11:19:12.299
!MESSAGE Starting the AWS toolkit core plugin...

!ENTRY com.amazonaws.eclipse.core 1 0 2016-04-14 11:19:15.497
!MESSAGE Monitoring content of /home/dylan/.aws/credentials

!ENTRY com.amazonaws.eclipse.core 1 0 2016-04-14 11:19:15.663
!MESSAGE AWS toolkit core plugin initialized after 3386 milliseconds.

!ENTRY com.amazonaws.eclipse.core 1 0 2016-04-14 11:19:15.681
!MESSAGE Found valid identity id cache us-east-1:83113660-ec5e-46c8-a587-83fe6095373c

!ENTRY org.eclipse.egit.ui 2 0 2016-04-14 11:19:22.250
!MESSAGE Warning: EGit couldn't detect the installation path "gitPrefix" of native Git. Hence EGit can't respect system level
Git settings which might be configured in ${gitPrefix}/etc/gitconfig under the native Git installation directory.
The most important of these settings is core.autocrlf. Git for Windows by default sets this parameter to true in
this system level configuration. The Git installation location can be configured on the
Team > Git > Configuration preference page's 'System Settings' tab.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.ui.browser 2 0 2016-04-14 11:19:43.635
!MESSAGE Internal browser is not available: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]

!ENTRY com.amazonaws.eclipse.core 1 0 2016-04-14 11:20:15.813
!MESSAGE Switching to global default account

!ENTRY com.amazonaws.eclipse.sdk.ui 1 0 2016-04-14 11:20:42.655
!MESSAGE Downloading the SDK from CloudFront to location /tmp/aws-java-sdk8075577366563612991/sdk.zip

!ENTRY com.amazonaws.eclipse.sdk.ui 1 0 2016-04-14 11:21:12.998
!MESSAGE SDK download completes. Location: /tmp/aws-java-sdk8075577366563612991/sdk.zip, File-length: 168026940

!ENTRY com.amazonaws.eclipse.core 1 0 2016-04-14 11:21:48.330
!MESSAGE Switching to global default account
```

**Comment by dylantuttle** [comment]
> Servers that were created in the AWS Management Console do not appear in the Toolkit for Eclipse

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/troubleshooting.html

> You can manually import servers by following the instructions at Importing Existing Environments into Eclipse.

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-eclipsetoolkit.html#create_deploy_Java.howto.importenv

Manually importing servers does not seem to work. I'm guessing that if I want to manage my environments in Eclipse in need to deploy from Eclipse. You may want to work this into the documentation somewhere.

**Comment by dylantuttle** [comment]
I was mistaken. I was not able to view the environments from the AWS Explorer view, but I am if I click on Open AWS Management Perspective. This was not obvious from the documentation, but I should have been able to figure it out. I'm sorry.
