### ISSUE TITLE
DynamoDB Explorer Doesn't Show Tables

### ISSUE THREAD

**Issue by parkej60** [aws/aws-toolkit-eclipse#43]
The DynamoDB Explorer doesn't show any tables unless I create them from within the explorer. Is there a way it can display the tables that I created through the AWS Console or CLI?

**Comment by fulghum** [comment]
Check and make sure you aren't working in different AWS regions.  The AWS Web Console might be defaulting you to a different region that what is selected in Eclipse.  The Eclipse tools will show you all your tables in the selected region, no matter what tool you used to create those tables.

**Comment by parkej60** [comment]
Thanks, will give it a try and let you know.

**Comment by zhangzhx** [comment]
Hey @parkej60,

Do you still see the problem? Feel free to reopen it if you have further questions.
