### ISSUE TITLE
Question: dynamoDB locally in docker container supported? 

### ISSUE THREAD

**Issue by henrjk** [aws/aws-toolkit-eclipse#44]
For testing I am running DynamoDB on my computer (OS X) inside a Docker container [trayio/dynamodb-local](https://github.com/trayio/dynamodb-local) as follows:

```
dev $ docker run -i -t -p 7777:7777 tray/dynamodb-local -inMemory -port 7777
```

With the aws cli I can access the local DynamoDB with the `--endpoint-url` parameter as follows:
```
dev $ aws dynamodb list-tables --endpoint-url http://$(docker-machine ip default):7777
TABLENAMES	     gamesdocker-machine ip default
# where 
dev $ docker-machine ip default
192.168.99.100
```

I tried to configure an AWS account from the AWS Explorer to do this but I could not find the correct option. It would be very cool to explore the local DynamoDB content with a UI. 
  
Is there some way to configure this?

**Comment by zhangzhx** [comment]
Hi henrjk, 

The AWS Explorer can start a local DynamoDB instance with a configured port number for you to do local test. However, it doesn't support to configure the IP and connect a remote DynamoDB instance. You can only connect DynamoDB in the public regions, such as US West (Oregon).

**Comment by fulghum** [comment]
henrjk – can you map the DynamoDBLocal port on your Docker instance directly onto a port on localhost?  That would let the Eclipse Toolkit connect to that port on localhost and access DynamoDBLocal.  Let us know how that goes.

**Comment by henrjk** [comment]
I managed to map the docker host port onto the Macs localhost as follows:

```
DMIP=$(docker-machine ip $DOCKER_MACHINE_NAME) ssh -i "$DOCKER_CERT_PATH/id_rsa" "docker@$DMIP" -N -L "7777:$DMIP:7777"
``` 

However I don't want to start a new local DynamoDB in AWS Explorer but use the one running in the Docker container. Can this be done?

**Comment by fulghum** [comment]
Try mapping the docker instance port to localhost:8000.  That's where the Eclipse Toolkit is expecting to find DynamoDBLocal running, so I *think* it'll just connect to that instance and not try to start a new instance.  Give that a shot and see if it works.

**Comment by henrjk** [comment]
This does not appear to work for me.  

I am still seeing the following:

![screen shot 2016-06-15 at 20 22 43](https://cloud.githubusercontent.com/assets/7439282/16092185/0cfdcc4a-3337-11e6-87d5-b5c59054370d.png)

**Comment by zhangzhx** [comment]
Hey henrjk,

The local DynamoDB instance will by default use separate databases for each credentials and region. You can start the DynamoDB instance by adding `--sharedDB` parameter.
Therefore, all clients will interact with the same set of tables, regardless of their region and credential configuration.

**Comment by zhangzhx** [comment]
Hey henrjk,

Does that resolve your problem? I'm closing this ticket for now and feel free to reopen if you still have problems.

**Comment by henrjk** [comment]
I have not tried your previous suggestion as I was interest using DynamoDb in unit tests using in memory mode. 
Thank you for your fast responses though!

**Comment by fvillegas** [comment]
> I have not tried your previous suggestion as I was interest using DynamoDb in unit tests using in memory mode.
> Thank you for your fast responses though!

@henrjk this work for me

![image](https://user-images.githubusercontent.com/461616/55432119-7c302300-5568-11e9-8eca-aca87857e916.png)
