### ISSUE TITLE
Having difficulties to set up a development environment

### ISSUE THREAD

**Issue by rherrmann** [aws/aws-toolkit-eclipse#46]
I got stuck after cloning this repository and importing all projects into a new workspace. 

There seems to be no target platform definition and I haven't found instructions how to setup the Eclipse IDE to make changes to the AWS Toolkit for Eclipse.

**Comment by zhangzhx** [comment]
We have migrated to Tycho build in a recently release and now you can directly clone the whole repository to your Eclipse workspace. Meanwhile, you can build and test the repository using Maven in the command line. See this [README](https://github.com/aws/aws-toolkit-eclipse/blob/master/README.md) file for more information.

**Comment by ChiroBan** [comment]
Gone through all the README steps. The second MVN command inside setup.sh file is giving the following list of errors:

**[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.amazonaws.eclipse.devide raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: com.amazonaws.eclipse.devide raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT requires 'org.eclipse.jst.web_sdk.feature.feature.group 0.0.0' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: com.amazonaws.eclipse:com.amazonaws.eclipse.devide:1.0.0-SNAPSHOT @ C:\Users\****\git\aws-toolkit-eclipse\releng\com.amazonaws.eclipse.devide\pom.xml: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException**

In need of some guidance with this.

**I have Tycho plugin installed in my Eclipse and I was able to import the entire AWS toolkit to my workspace. I just want to setup a development environment and test the custom plugin in EClipse IDE.

**Comment by ChiroBan** [comment]
I have solved the problem. I will be happy to help if anyone is having any related issues with setting up the target platform or development environment in Eclipse.

**Comment by lak-proddev** [comment]
To fix this problem you need to add required features or plugins to the target platform. 
See the below SS

![image](https://user-images.githubusercontent.com/39690425/57016334-3766dd00-6c37-11e9-89fd-e98e53d1e56c.png)

The highlighted features in the above SS are unresolved features. 

Actually, the development setup is a little bit confusing. the suggest target definition for **Photon** environment is 
[com.amazonaws.eclipse.photon.zip](https://github.com/aws/aws-toolkit-eclipse/files/3134458/com.amazonaws.eclipse.photon.zip)

**Comment by Shinehah-Gnolaum** [comment]
@lak-proddev I don't see the same libraries.

**Comment by Shinehah-Gnolaum** [comment]
@lak-proddev What exactly are you doing in that screenshot? How do you resolve the unresolved features?

**Comment by lak-proddev** [comment]
You need to add the attached "target definition" file as a target platform.  This article helps you to define a target platform.
https://www.vogella.com/tutorials/EclipseTargetPlatform/article.html
You need to create a new general project in your workspace and copy the attached target definition file.

**Comment by Shinehah-Gnolaum** [comment]
@lak-proddev What target definition file? I know nothing about a target definition file.

**Comment by Shinehah-Gnolaum** [comment]
@lak-proddev My actual issue is issue #145.

**Comment by zhangzhx** [comment]
@Shinehah-Gnolaum , the target definition file is used to develop plugins, in this case the AWS Eclipse Toolkit plugin. If you just want to install and use the plugin, you don't have to understand the target definition file.
