### ISSUE TITLE
Need to acknowledge the same license twice when installing AWS Toolkit for Eclipse

### ISSUE THREAD

**Issue by rherrmann** [aws/aws-toolkit-eclipse#47]
Steps:
1. open the _Install New Software_ dialog and enter https://aws.amazon.com/eclipse
2. select the _AWS Core Management Tools_ and _AWS Deployment Tools_
3. press _Next_ and again _Next_

On the upcoming page, there are two licensess to be accepted that are apparently the same Apahce v2 licnese. One of them should be enough.

![image](https://cloud.githubusercontent.com/assets/607182/20561099/0f93a23a-b17d-11e6-9cf5-4443d5ce732c.png)

**Comment by fulghum** [comment]
This is an artifact of some third-party code (json.org) that's embedded in the AWS SDK for Java.  The second Apache license file actually has an attribution for the json.org code at the very end of the license.  It's something we'd like to clean up in the AWS SDK for Java.  We aren't using the json.org code for much anymore – we're almost exclusively using Jackson.  I'll check in with the team and see how much code we have left depending on the json.org classes.  We've been wanting to clean that up for a while; it just hasn't bubbled up to be a priority yet.

**Comment by shorea** [comment]
We dropped JSON.org in 1.11.0.

**Comment by fulghum** [comment]
Thanks for the update Andrew.  Sounds like we just need to update the attribution in the SDK and get the latest version into the Eclipse Toolkit and this will go away.

**Comment by fulghum** [comment]
Actually... the plot is thickening on this one... we've removed json.org and it's attribution; it's not mentioned in the SDK's license file or in the Eclipse license file.  @zhangzhx will dig in a little deeper and find out exactly what's different here and we'll get this cleaned up.

**Comment by zhangzhx** [comment]
The core plugin has some files under EPL 1.0. See [here](https://github.com/aws/aws-toolkit-eclipse/blob/master/com.amazonaws.eclipse.core.feature/feature.xml#L206-L277). We'll clean these files up. Thanks for the report.

**Comment by rherrmann** [comment]
To my knowledge, the different licenses of all features to be installed are listed in this context. Different, here, means that the text given in `<license>` element in the `feature.xml` differs - if only slightly. 

A [_license feature_](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_shared_license.htm) may help here to avoid (slightly different) duplicates.

**Comment by zhangzhx** [comment]
I have rewritten the code under EPL and removed the EPL declaration. So the new version of the toolkit only has Apache license.
