### ISSUE TITLE
New AWS Lambda wizard should assist when no AWS SDK installed

### ISSUE THREAD

**Issue by rherrmann** [aws/aws-toolkit-eclipse#48]
When trying to create an AWS Lambda project forthe first time, I see the following error message:

> The selected input type requires the AWS Java SDK dependency. Please install the SDK first (Window -> Preference -> AWS Toolkit -> AWS SDK for Java) and then retry.

To solve the problem, I need to close the _New AWS Lambda_ wizard (thereby discarding all input I already made), memorize the path the the preference page and finally open the page.

It would help if there was some sort of a link to open the preference page

**Comment by fulghum** [comment]
Ouch.  That's not very smooth.  This sounds like another good argument to switch to a Maven project structure and let Maven do the dependency caching/resolution, rather than forcing developers to do extra work to make dependencies available.  I'm interested to hear your thoughts on that.  See any downsides to switching to a Maven project structure?

**Comment by rherrmann** [comment]
I absolutely agree with you to re-use existing tools for dependency resolution. While Maven is a popular choice, Gradle also becomes more and more popular these days. Hence you may want to give users a choice which project layout/build tool they want to create a project for. However, you probably know best what build tool the majority of your users use.

Maybe a list of project layouts to choose from in the existing New AWS Project wizard would be decent solution. Specific 'project creators' could be contributed through extensions. 

Support for a specific build tool would probably require a dependency on the respective Eclipse plug-ins (i.e. m2e or Buildship). In this case, the plug-ins that provide the contributions would need to be optional so that installing the AWS Toolkit does not drag in all the build tool dependencies.

**Comment by zhangzhx** [comment]
We have changed to using Maven to manage the dependencies for AWS Java SDK as Maven is still the most popular tool for developers. But as Gradle is having more and more adopters, we might consider to provide Gradle support as well in the future.
