### ISSUE TITLE
AWS Lambda Function runtime has no source attachment

### ISSUE THREAD

**Issue by rherrmann** [aws/aws-toolkit-eclipse#49]
Steps:
1. create a new AWS Lambda project
2. in the generated `LambdaFunctionHandler`, navigate the method declaration and open the `Context` type.

Instead of showing the source code, only the class file editor opens. Having access to source code helps in many situations, such as debugging, unclear JavaDoc, etc. Besides that, there should be source attachements for consistency reasons as other AWS libraries come with sources.

**Comment by fulghum** [comment]
Great suggestion.  On a related note... we've been considering switching these project types to Maven projects that would declare this dependency in the POM.  That should simplify things overall, and we could let Maven take care of attaching the source for dependencies.

**Comment by Mutley5000** [comment]
Changing the projects types to Maven would also make packaging the projects for deployment nicer.

**Comment by zhangzhx** [comment]
Guess what, I am working on changing the project to Maven right now :) This change will be released next week or so.

**Comment by Mutley5000** [comment]
Awesome! Look forward to it.

**Comment by zhangzhx** [comment]
Sorry for the late reply. This had been released on Feb 2017. Please try the new version and let us know what you think. We appreciate your feedbacks.
