### ISSUE TITLE
Toolkit Analytics preference page is overly wide

### ISSUE THREAD

**Issue by rherrmann** [aws/aws-toolkit-eclipse#50]
Clicking through the AWS preference pages, when I hit the _Toolkit Analytics_ page the entire dialog expands horizontally (see below).

![image](https://cloud.githubusercontent.com/assets/607182/20562913/717df8c0-b186-11e6-91c3-eb3fead5498d.png)

**Comment by fulghum** [comment]
Thanks for reporting this Rüdiger!  This is definitely not the way we want this preference page laid out. :-)  We'll get text wrapping correctly.

**Comment by zhangzhx** [comment]
This has been fixed in the latest release [v201710120027](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201710120027).
