### ISSUE TITLE
authentication S3 server

### ISSUE THREAD

**Issue by linerdong** [aws/aws-toolkit-eclipse#55]
when I use AmazonS3Client to connect amazon s3, Does the sdk authenticate S3 server? for example, it will authenticate the ca certificate of amazon

**Comment by zhangzhx** [comment]
Yes, it is. See the detailed description for how to configure this [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/SDKGlobalConfiguration.java#L23-L32).
