### ISSUE TITLE
Add ability to specify AWS KMS master key for Upload function to AWS Lambda

### ISSUE THREAD

**Issue by Mutley5000** [aws/aws-toolkit-eclipse#56]
I think it would be useful to add the ability to specify a AWS KMS master key for those that use server side encryption so that Lambda functions can be uploaded to S3 straight from the IDE using the Upload function to AWS Lambda option given by the AWS Lambda plugin.

**Comment by zhangzhx** [comment]
Hi Mutley5000,

That's a very great callout. Thanks for the feedback, I will add this feature to our backlog and will let you know once this feature is released.

**Comment by Mutley5000** [comment]
Hey zhangzhx,

No worries.  Glad to help!

**Comment by zhangzhx** [comment]
This has been released in the latest version [v201709262229](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201709262229).
