### ISSUE TITLE
Add ability to support publishing version on Lambda

### ISSUE THREAD

**Issue by garvitsingh-aws** [aws/aws-toolkit-eclipse#58]
it would be helpful to be able to make use of UpdateFunctionCode API to make code update and publishing version on Lambda as an atomic call
currently, i don't see this is supported

**Comment by fulghum** [comment]
Thanks for the feedback.  Can you tell us a little more about your use case?  How would you expect this to be exposed in Eclipse?

**Comment by gsinghlab** [comment]
I believe its a simple use case, when you use aws-toolkit lambda function, it allows you to upload the lambda code, and it replaces $LATEST version. If we could get an option to publish version along with updating code, so in aws console you can see the newer version when you update code.

**Comment by zhangzhx** [comment]
This has been released in the latest version [v201709262229](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201709262229). Please try it out and let us know what you think.
