### ISSUE TITLE
The plugin installation is failing from Marketplace in Eclipse Neon Version.

### ISSUE THREAD

**Issue by Chandra-TechPassionate** [aws/aws-toolkit-eclipse#59]
The plugin installation is failing from Marketplace in **Eclipse Neon** Version.

**Comment by fulghum** [comment]
Could you share the error message you got?  We'll try to repro the issue over here, too, but an error message would give us a good lead to start with.

**Comment by zhangzhx** [comment]
I've tried this on Mac and not seeing this issue. Can you share more information to us? Also, does the update site work for you?

**Comment by Chandra-TechPassionate** [comment]
The installation worked this time. I found **PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException** during connect and download, and have fixed it.

**Comment by zhangzhx** [comment]
Glad to hear that. :) Let us know if you have any feature requests or bug reporting when using the AWS Toolkit for Eclipse. We appreciate your comments.
