### ISSUE TITLE
EC2 Instance names

### ISSUE THREAD

**Issue by mcacker** [aws/aws-toolkit-eclipse#61]
Unless i'm missing something, there doesn't appear to be a way to easily see the EC2 Instances names.  There is no column for it, or no way to add a column for it.  Ok, you can see it in the tags, but for me it's buried in there amongst other tags.

The AWS Console recognizes the utility of this, why not the eclipse plugin?  I, for one, would like to see a name column, or an easy way to customize the table.

**Comment by zhangzhx** [comment]
Thanks Mitchell for this feature request. We'll consider adding this feature shortly. I'll let you know once it's been released!

**Comment by zhangzhx** [comment]
This feature has been published in the latest release [v201708161930](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201708161930).
