### ISSUE TITLE
"There are no items available" for Eclipse Neon.1a Release (4.6.1) 

### ISSUE THREAD

**Issue by shevken** [aws/aws-toolkit-eclipse#62]
Hi,

I couldn't see any items after entering the update site.

Version: Eclipse Java EE IDE for Web Developers, Neon.1a Release (4.6.1)
Site: https://aws.amazon.com/eclipse

Cheers,
Kenny

**Comment by zhangzhx** [comment]
Sorry for the inconvenience you met. We've noticed this problem before and you can try [these options](http://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/setup-install.html#upgrade-the-tke) to see if it could resolve your problem. I've pasted as below:

> To upgrade or reinstall the AWS Toolkit for Eclipse, use the same instructions for installing the toolkit.
> 
> Some versions of Eclipse, (notably Mars and Neon), may fail to fetch the latest artifacts due to a bug in old versions of the Oomph plugin. To work around this issue:
> 
> - Make sure that you're using https://aws.amazon.com/eclipse/site.xml as the AWS Toolkit for Eclipse update site.
> - Delete the ~/.eclipse/org.eclipse.oomph.p2/cache/ directory to remove cached content.
> - Install the latest version of Oomph (Eclipse Installer).

Let me know if you still have any problem.

**Comment by shevken** [comment]
Hi Ms Zhang,

I have seen and tried the options you pasted already before I had created this issue. Does not really work.
I am using the latest Oomph version (1.7.0.v20170305-1123)

Cheers,
K

**Comment by zhangzhx** [comment]
Hmm, that's really weird! What OS are you in? Also, what JDK version have you installed?

**Comment by zhangzhx** [comment]
Do you still see this problem? I'm resolving this issue for now. Feel free to open a new one if you still have problems.

**Comment by SantoshNII** [comment]
@zhangzhx I have followed the above mentioned steps, I am still facing the issue.
