### ISSUE TITLE
Cannot associate tags when starting CF stack

### ISSUE THREAD

**Issue by rdettai** [aws/aws-toolkit-eclipse#63]
I noticed it is not possible to add tags when launching a CloudFormation stack. This is very annoying as tags are very convenient to manage costs.

This is how it currently appears in the console:
![image](https://cloud.githubusercontent.com/assets/7913347/25337444/2d8f0ed6-28fc-11e7-8b6c-9f6a8b316912.png)

**Comment by zhangzhx** [comment]
Thanks for reaching out to us. This is a good feature request for AWS Toolkit for Eclipse. We'll consider adding this feature. I'll let you know once that is released.

**Comment by zhangzhx** [comment]
This feature has been added in the latest version [v201707121824](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201707121824)
