### ISSUE TITLE
ResourceType IllegalArgumentException

### ISSUE THREAD

**Issue by philippebailer** [aws/aws-toolkit-eclipse#64]
I have defined an AIM role in my template which fails with: `Cannot create enum from AWS::IAM::Role value!` when "deploying serverless project..." through the eclipse interface.

The confusing part is that if you just call create stack on the template it works fine the issue comes when trying to deploy as a serverless project.

The error comes from the [ResourceType](https://github.com/aws/aws-toolkit-eclipse/blob/master/bundles/com.amazonaws.eclipse.lambda/src/com/amazonaws/eclipse/lambda/serverless/model/ResourceType.java) Enum which contains a TODO for Ideally, supporting all the resources supported by CloudFormation.

The error actually occurs during a [this](https://github.com/aws/aws-toolkit-eclipse/blob/master/bundles/com.amazonaws.eclipse.lambda/src/com/amazonaws/eclipse/lambda/serverless/Serverless.java#L130) method where you are passing through all types except AWS_SERVERLESS_FUNCTION.

Once you get to Serverless.convert(ServerlessModel) to output a ServerlessTemplate you are still just passing through the data and then writing it to a file which is then saved to s3 and ran in cloudformation.

So from what I am seeing you are only ever generating any additional data if the ResourceType is AWS_SERVERLESS_FUNCTION and all others are just pass through. Is there an issue with just adding the enums to support AIM and StepFunctions types or any other type for that matter?

Or rather then adding extra enums you could just remove/catch the error so that unknows types just pass through. This would allow the tool to support newer features without requiring an update. The point of the tool is to do some magic on Serverless ResourceTypes but thats all it should be doing right? The rest of the file should be passed as is?

Or is there a workaround to this that I am just missing completely?

Thank you for your help.

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. This seems to be a feature request for Serverless deployment or could be regarded as a bug.

You are right that "The point of the tool is to do some magic on Serverless ResourceTypes but thats all it should be doing right? The rest of the file should be passed as is?". You are reporting this issue just about the right time. We are working on fixing known bugs and adding new features in Serverless and we'll fix this one. I'll let you know once this one is fixed.

**Comment by philippebailer** [comment]
Thats great, thanks for the quick response.

**Comment by zhangzhx** [comment]
This has been fixed in the [latest release v201708041710](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201708041710).
