### ISSUE TITLE
Unable to connect to local DynamoDB

### ISSUE THREAD

**Issue by conTroll** [aws/aws-toolkit-eclipse#65]
With the current version installed from the update site (and also from the Marketplace) when I select the region "Local" in AWS Explorer, and start the local dynamo db server I can't connect to it (Unable to connect). When trying to create a table, it can be seen that it always tries to connect to port 8000, regardless of the actual port the server listens on. Additionally it tries to use HTTPS instead of HTTP so it can't connect even when the server runs on port 8000. The last correctly working version was 2.3.1.v201704240512

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. This seemingly like a regression. I will submit a fix in the next release.

**Comment by zhangzhx** [comment]
Hey @conTroll,

We have fixed this in the new release **v201705232324**. Please upgrade and let us know if you still see this problem. Thank you.

**Comment by franciscocpg** [comment]
I was with the same problem and after some googling I ended up here.
I can confirm that after upgrading AWS toolkit the bug was fixed.
