### ISSUE TITLE
[Feature request] [AWS Eclipse toolkit] -  Upload function to AWS Lambda - AES256 encryption issue

### ISSUE THREAD

**Issue by datteswararao** [aws/aws-toolkit-eclipse#66]
I would like to request a new feature:

Encryption option for "upload function to AWS Lambda" in AWS Eclipse toolkit

AWS Eclipse - Java Lambda upload to S3 - AES256 encryption issue

I'm having trouble to upload changes of my Java project in local machine Eclipse to S3 Bucket (AES256). I know the zip file, I'm trying to upload is not encrypted and i'm trying to upload to an encrypted bucket in S3. 

Below the error:

Uploading function code to dumpjump...
==================== INVOCATION ERROR ====================
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: A0AB746C98F66FF3), S3 Extended Request ID: 23LtcxnfpXkamHXt411Atr5j1LlRj5Mq+cQ+1D0kWuFPWgcVXybwmwgT3i07o7JY3BwIYbCIVSk=

Ask:

How can I setup "upload function to AWS Lambda" option to send the file with Server side encryption? from eclipse AWS plug-in.

Is there any options or setting in ECLIPSE AWS Java plugin will allow me to upload the Java Lambda function to S3 with AES256?

**Comment by zhangzhx** [comment]
This has been released in the latest version [v201709262229](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201709262229). Please try it out and let us know your thoughts.
