### ISSUE TITLE
Using dark theme makes "Blue" string color unreadable in AWS Management Perspective

### ISSUE THREAD

**Issue by azimmerman0125** [aws/aws-toolkit-eclipse#67]
When using the AWS-Toolkit-Eclipse project, I have a custom "Dark" Theme with a dark / black background.    The "String" functionality is displayed as "Blue" but is unreadable against the dark background when editing a cloud formation template.

Please provide a way to either change the "String" color or modify the blue color to be easier to read against a dark background as well as "white" background.

**Comment by zhangzhx** [comment]
The preference page for setting the syntax coloring is included in release [v201707121824](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201707121824). Feel free to try the new version and let us know what you think.
