### ISSUE TITLE
Enable Curly Brackets and Quotes Matching  in AWS Management Perspective

### ISSUE THREAD

**Issue by azimmerman0125** [aws/aws-toolkit-eclipse#68]
When working with the standard AWS Management Perspective in Eclipse, Curly Brackets or Single / Double Quotes Matching is not available as an option.  It makes troubleshooting JSON cloudformation templates a challenge.

It would be great if this functionality could be added

**Comment by fulghum** [comment]
Thanks for reporting this; it sounds like a great feature request for the CloudFormation template editor.

Let us know if you've run into other issues or missing features for the CloudFormation editor, or any other parts of the AWS Toolkit for Eclipse.  We love hearing customer feedback and strongly rely on it for prioritizing updates.

**Comment by azimmerman0125** [comment]
Thanks for considering this and I'll be sure to add any additional features / issues.

**Comment by zhangzhx** [comment]
This feature has been added to the latest release [v201707121824](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201707121824). Feel free to try this out and let us know what you think.
