### ISSUE TITLE
Eclipse AWS Explorer can't see Dyanmodb tables created with Java

### ISSUE THREAD

**Issue by dwschulze** [aws/aws-toolkit-eclipse#69]
I'm trying to use AWS Explorer in Eclipse but it doesn't show newly created tables. When I use [this Java sample code](http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.Java.01.html)  to create a table AWS Explorer doesn't show the new table after refreshing. It doesn't show it in either the local or us-west-2 region. If I run the code again it throws an Exception saying "Cannot create preexisting table ..." so the Movies table was created. If I change the second parameter in

new AwsClientBuilder.EndpointConfiguration("http://localhost:8000", "us-west-2")

by deleting the '2' I can run again successfully. Running a second time gives the same error.  The JavaDoc doesn't say what the second parameter is supposed to do when I'm using a local DynamoDB.

The Java code apparently is creating the Movie table somewhere else than where AWS Explorer is looking. I've also tried RazorSql and it doesn't see the Movie table either. Both see tables created with AWS Explorer though.

It looks like the local instance of DynamoDB shows something different to AWS Explorer and RazorSql than what Java code accesses.

**Comment by zhangzhx** [comment]
Hey @dwschulze ,

Thanks for reporting this issue. We have fixed this in the latest release **v201705232324**. Please upgrade and let us know if you still see this problem.

Notice that the Eclipse Dynamodb explorer is using "local" as the region name for accessing local dynamodb. Please update
`new AwsClientBuilder.EndpointConfiguration("http://localhost:8000", "us-west-2")` to 
`new AwsClientBuilder.EndpointConfiguration("http://localhost:8000", "local")` accordingly to show the tables in Eclipse Dynamodb explorer.

Let us know if you still have problems and any ideas for new features as well.

**Comment by edgartabz** [comment]
What I did was I created a symbolic link in the local dynamodb directory e.g.:

AKIAIJTQ7SO7LQOPW4BA_local.db <<===>> AKIAIJTQ7SO7LQOPW4BA_us-west-2.db
