### ISSUE TITLE
AWS Type in Parameters is not "pink" like in Resource 

### ISSUE THREAD

**Issue by azimmerman0125** [aws/aws-toolkit-eclipse#70]
When using the Aws Management Perspective the following occurs when using the JSON formation.

  "Parameters" : {
    "EngineSecurityGroupId" : {
      "Description" : "Enter the ELB Security Group to give Access to the Instance(s)",
      "Type" : "AWS::EC2::SecurityGroup::Id"
    }, 
    ....
}

The AWS::EC2::SecurityGroup::Id is blue for string not pink for AWS Type.  See 
  "Resources" : {
    "InstanceSG00" : {
      "Type" : "AWS::EC2::SecurityGroup",
    ...
  }

**Comment by zhangzhx** [comment]
The reason why **AWS::EC2::SecurityGroup::Id** is not colored pink is because we only pink AWS Resources defined [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html). It is not an AWS resource type in this case.

**Comment by azimmerman0125** [comment]
Zhaoxi,

Thanks for that answer.  Makes sense.

Regards,

Adam
