### ISSUE TITLE
No choice in picking the Lambda function to run when setup as a AWS Lambda Java Project. 

### ISSUE THREAD

**Issue by boomkap** [aws/aws-toolkit-eclipse#72]
When creating an AWS Lambda Java Project in Eclipse with multiple Lambda functions, when the user chooses to run a particular function, there is no choice to pick the Lambda function to run. 
It runs the last uploaded function. This is very limiting and forces user to keep uploading the function before they can run it.

**Comment by zhangzhx** [comment]
Thanks for reaching out to us. I will add this feature to our backlog and let you know once it's released.

**Comment by boomkap** [comment]
Thanks. I also ran into another issue will be sending email shortly on that.

**Comment by zhangzhx** [comment]
Sure, feel free to cut another issue if it is not related to this one. :)

**Comment by boomkap** [comment]
I followed the tutorial for AWS lambda listed on the following URL: 
http://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/lambda-tutorial.html

The function uploaded without any issue. However when I go to execute the function, this is the error I get. 

Uploading function code to HelloLambda...
Upload success. Function ARN: arn:aws:lambda:us-east-1:xxxxxxxxx:function:HelloLambda
Invoking function...
==================== INVOCATION ERROR ====================
com.amazonaws.services.lambda.model.InvalidRequestContentException: Could not parse request body into json: Invalid UTF-8 start byte 0x80
at [Source: B@46625e69; line: 1, column: 3 (Service: AWSLambda; Status Code: 400; Error Code: InvalidRequestContentException; Request ID: 2af05a4f-618c-11e7-b0a0-f3498091a143)

I am passing "Hello World!" as my input string. 


This is my class. 

package example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class Hello implements RequestHandler<String, String> {

    @Override
    public String handleRequest(String input, Context context) {
        context.getLogger().log("Input: " + input);

        // TODO: implement your handler
        return "Hello from Lambda! "+input;
    }

}

**Comment by zhangzhx** [comment]
This has been released in the latest version [v201709262229](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201709262229). Please try it out and let us know your thoughts.
