### ISSUE TITLE
Issue with the Lambda Tutorial for the Eclipse Toolkit.

### ISSUE THREAD

**Issue by boomkap** [aws/aws-toolkit-eclipse#73]
I followed the tutorial for AWS lambda listed on the following URL:
http://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/lambda-tutorial.html

The function uploaded without any issue. However when I go to execute the function, this is the error I get.

Uploading function code to HelloLambda...
Upload success. Function ARN: arn:aws:lambda:us-east-1:xxxxxxxxx:function:HelloLambda
Invoking function...
==================== INVOCATION ERROR ====================
com.amazonaws.services.lambda.model.InvalidRequestContentException: Could not parse request body into json: Invalid UTF-8 start byte 0x80
at [Source: B@46625e6; line: 1, column: 3 (Service: AWSLambda; Status Code: 400; Error Code: InvalidRequestContentException; Request ID: 2af05a4f-618c-11e7-b0a0-f3498091a143)

I am passing "Hello World!" as my input string.

This is my class.

package example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class Hello implements RequestHandler<String, String> {

    @Override
    public String handleRequest(String input, Context context) {
        context.getLogger().log("Input: " + input);

        // TODO: implement your handler
        return "Hello from Lambda! "+input;
    }

}

**Comment by zhangzhx** [comment]
Hey @boomkap , could you double check whether the content encoding is UTF-8 or not? It's seems that the "Hello World" you provided is not encoded in UTF-8 that the AWS Lambda cannot parse it correctly.

Let me know if you have any questions.

**Comment by boomkap** [comment]
I am just typing the string in the Eclipse dialog box that comes up when using the AWS —> Run Function on Lambda. 

Do you want me to check for the encoding somewhere in the Eclipse —> preferences? If so, let me know where.  

Thanks,
—Kapil

**Comment by zhangzhx** [comment]
Can you take a look at this https://stackoverflow.com/questions/33607828/how-to-change-the-default-default-encoding-in-eclipse to update the default encoding?

I'm not 100% sure whether it is because of this, but it seems that you have a weird encoding issue that the AWS Lambda doesn't recognize the input as a valid UTF-8 string.

**Comment by boomkap** [comment]
My workspace is UTF-8. See attached screenshot. That does not seem to be the issue. 


com.amazonaws.services.lambda.model.InvalidRequestContentException: Could not parse request body into json: Unrecognized token 'String': was expecting ('true', 'false' or 'null')

The error I get is not encoding related. Its expecting a String thats a valid JSON. Not sure why…

**Comment by zhangzhx** [comment]
Is the string **"Hello World"** or just **Hello World**? You need to provide the double quotes as well.

**Comment by boomkap** [comment]
Even the string Hello gives me the same error.

**Comment by zhangzhx** [comment]
Did you provide the double quotes mark? You cannot just use the bare literals. They must be quoted as a String type that could be recognized as a valid Json format.

**Comment by boomkap** [comment]
If I type in double quotes, I get the following error. This one hints at an Invalid UTF-8 character. Really weird. 

com.amazonaws.services.lambda.model.InvalidRequestContentException: Could not parse request body into json: Invalid UTF-8 start byte 0x80

**Comment by zekefooser** [comment]
I figured out what's happening. When you type what you think is a double quote, the Eclipse editor changes the character from a standard double quote to the fancier looking double quote. What i did was type the quoted string on vi, and then copied and pasted into the Eclipse editor. Then i was able to run the lambda example.

**Comment by zhangzhx** [comment]
Thanks for taking time to figure this out. It looks like an OS level issue. A similar discussion here:
https://apple.stackexchange.com/questions/120486/quotes-problem-in-mavericks-or-textedit

It looks like you can change some System settings for changing this behavior.

Resolving this issue as it is not Eclipse related. Feel free to open a new one if you still see more problems about this.

**Comment by vinodborole** [comment]
I faced similar issue, its because of the OS Settings for apple with smart quotes; @zhangzhx  the latest post solved it for me. Thanks
