### ISSUE TITLE
eclipse php (oxygen) couldn't install this plugin.

### ISSUE THREAD

**Issue by Galleria** [aws/aws-toolkit-eclipse#76]
I tried to install and found an error as below.

> Cannot complete the install because one or more required items could not be found.
> Software currently installed: AWS Toolkit for Eclipse Core (Required) 2.3.1.v201707121824 (com.amazonaws.eclipse.core.feature.feature.group 2.3.1.v201707121824)
> Missing requirement: AWS Toolkit Core Plugin 2.3.1.v201707121824 (com.amazonaws.eclipse.core 2.3.1.v201707121824) requires 'bundle org.eclipse.m2e.core 1.5.1' but it could not be found
> Cannot satisfy dependency:
> From: AWS Toolkit for Eclipse Core (Required) 2.3.1.v201707121824 (com.amazonaws.eclipse.core.feature.feature.group 2.3.1.v201707121824)
> To: com.amazonaws.eclipse.core [2.3.1.v201707121824]

for eclipse information
>Eclipse for PHP Developers
> Version: Oxygen Release (4.7.0)
> Build id: 20170620-1800

could you please help me for this issues ?
thanks,

**Comment by zhangzhx** [comment]
It seems that the Eclipse for PHP distribution does not have m2e plugin installed by default. Can you install the m2e plugin first. Here is the update site for m2e http://download.eclipse.org/technology/m2e/releases

Let me know if you still have problems.

**Comment by Galleria** [comment]
after installed m2e [I](http://download.eclipse.org/technology/m2e/releases) found an error  
> Cannot complete the install because one or more required items could not be found.
> Software currently installed: Amazon RDS Management 1.0.0.v201707121824 (com.amazonaws.eclipse.rds.feature.feature.group 1.0.0.v201707121824)
> Missing requirement: Amazon Relational Database Service (RDS) Plugin 1.0.0.v201707121824 (com.amazonaws.eclipse.rds 1.0.0.v201707121824) requires 'bundle org.eclipse.datatools.connectivity.ui.dse 1.1.0' but it could not be found
> Cannot satisfy dependency:
> From: Amazon RDS Management 1.0.0.v201707121824 (com.amazonaws.eclipse.rds.feature.feature.group 1.0.0.v201707121824)
> To: com.amazonaws.eclipse.rds [1.0.0.v201707121824]

Then I tried installing list as below from ([](http://aws.amazon.com/eclipse/)) and it works !!
- AWS core management Tools
- AWS deployment Tools
- Optional - AWS Data Management Tools
Thanks,
@zhangzhx thank you very much,

**Comment by zhangzhx** [comment]
Glad to hear that. Please let us know what you think about the toolkit. Feel free to leave any comment or feature request here if any :)
