### ISSUE TITLE
AWS Lambda Java S3 Project

### ISSUE THREAD

**Issue by imrantariq** [aws/aws-toolkit-eclipse#77]
One of the error log in AWS Lambda Java S3 Project "aws-toolkit-eclipse\bundles\com.amazonaws.eclipse.lambda\code-template\lambda" prints wrong information. It prints bucketName instead of key in logs which can create confusion

**Comment by imrantariq** [comment]
Can I fix it and contribute in code commit?

**Comment by fulghum** [comment]
Sure! We love getting pull requests and contributions.

**Comment by zhangzhx** [comment]
This is included in the latest release [v201708161930](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201708161930). Thanks for the contribution.
