### ISSUE TITLE
When browsing many many DynamoDB tables, it would be very useful to be able to specify a filter to reduce the number of visible tables

### ISSUE THREAD

**Issue by mwnorman** [aws/aws-toolkit-eclipse#8]

**Comment by zhangzhx** [comment]
Closing this issue for the long time spanning. If you still want this feature, can you cut a new issue? Thank you.

As the AWS Console is more prone to managing AWS resources with UI, the AWS Toolkit for Eclipse is more prone to providing convenience for AWS development. So we might be de-prioratize features like this.
