### ISSUE TITLE
S3 Delete  No/Yes button labels are backwards

### ISSUE THREAD

**Issue by mmunn1** [aws/aws-toolkit-eclipse#80]
The pop up question "Are you sure you want to delete the selected  buckets" has the Yes/No labels backwards. To delete and object or bucket you must select  "No" it should be "Yes",  it appears to just be a matter of switching the button text properties.   Yes/No as opposed to No/Yes

**Comment by zhangzhx** [comment]
This has been released in [v201709081818](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201709081818). Closing this issue.
