### ISSUE TITLE
Temporary credentials does not refresh for new credential file

### ISSUE THREAD

**Issue by dwhip** [aws/aws-toolkit-eclipse#82]
I am experiencing problems with the AWS Toolkit Eclipse plugin with temporary credentials.  I have created a file in my ~/.aws folder with aws_access_key_id, aws_secret_access_key, and aws_session_token values.

It will work fine until these credentials expire.  Then I get new temp credentials and update the credentials file.  

Eclipse asks me if I want to refresh the credentials, and I say yes, but it is still unable to connect.  

If I look at the credentials page in the Windows -> Preferences -> AWS Toolkit page, I do see that the credentials they list are updated, but the AWS Explorer still says no connection.

I have to stop and restart Eclipse for the new credentials to actually take effect.

I have tried deleting the credentials file.  Eclipse then says I do not have them configured, but if I run process to create a new credentials file with temporary credentials, it still cannot connect until I stop and restart eclipse.

Eclipse seems to know about the file update, but the credentials being held do not seem really get updated.

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. We'll take a look at this issue and submit a fix in the next release.

**Comment by zhangzhx** [comment]
This has been fixed in the latest release [v201710120027](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201710120027). Please try the new version and let us know if you have any questions.
