### ISSUE TITLE
HTTP Server Unknown HTTP Response Code (301) When Installing File

### ISSUE THREAD

**Issue by TheDemin** [aws/aws-toolkit-eclipse#85]
I am unable to access your AWS Toolkit for Eclipse 2.0. Every time I try to download it from the Marketplace, I get an error message stating, 

“HTTP Server Unknown HTTP Response Code (301):http://aws.amazon.com/eclipse/site.xml/content.xml
General connection error with response code=301”

I have also attempted to follow the instructions here ( https://aws.amazon.com/eclipse/ ). However, I get this error twice :

 HTTP Server Unknown HTTP Response Code (301):https://aws.amazon.com/eclipse/site.xml
HTTP Server Unknown HTTP Response Code (301):https://aws.amazon.com/eclipse/site.xml
General connection error with response code=301

With Eclipse noting that it is an org.eclipse.equinox.p2.core.ProvisionException exception.

I am running a Eclipse Mars Release 4.5.0 on a Windows 7.

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. There are a lot of discussions about issues like this.

* https://groups.google.com/forum/#!topic/emacsplus/OLhSn8402VI
* https://stackoverflow.com/questions/45681619/error-while-downloading-plugin-from-eclipse-oxygen

It still seems to me a network issue for your Internet settings. Are you using any proxies for your Internet? Can you ping aws.amazon.com correctly? If by any means, it doesn't work, you can download the latest binary archive for the plugins [HERE](https://github.com/aws/aws-toolkit-eclipse/releases/download/v201709262229/aws-toolkit-for-eclipse-v201709262229.zip). Install it back in Eclipse by selecting **Help** -> **Install New Software**, then click on **Add..** -> **Archive..**, then select the archive file you just downloaded and continue on by following the instructions.

**Comment by TheDemin** [comment]
I have downloaded the latest binary archive for the plugins, and followed the steps. It worked like a charm, thank you for your assistance.
