### ISSUE TITLE
Ability to add/set capabilities to CAPABILITY_NAMED_IAM in serverless project.

### ISSUE THREAD

**Issue by NormanNordstrom** [aws/aws-toolkit-eclipse#87]
It would be great to be able to set the ”--capabilities” parameter inside of an AWS Serverless Project to "CAPABILITY_NAMED_IAM" instead of the defalut "CAPABILITY_IAM" or even set both.
 
In my serverless template I tried to create an IAM Role and then use the "RoleName". But it would fail because I could not also set "CAPABILITY_NAMED_IAM" on the capabilities.

**Comment by zhangzhx** [comment]
Thanks for reaching out to us. We'll add this to our backlog and letting you know once it is released.

**Comment by zhangzhx** [comment]
This has been included in the [release](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201801042359). Thanks for the request.
