### ISSUE TITLE
Exception When Attempting to Debug Sam Local Project

### ISSUE THREAD

**Issue by byamabe** [aws/aws-toolkit-eclipse#91]
java.lang.RuntimeException: Failed to launch Eclipse Debugger at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:129) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739) at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039) at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: org.eclipse.core.runtime.CoreException: Failed to connect to remote VM at org.eclipse.jdt.internal.launching.SocketAttachConnector.abort(SocketAttachConnector.java:98) at org.eclipse.jdt.internal.launching.SocketAttachConnector.connect(SocketAttachConnector.java:157) at org.eclipse.jdt.internal.launching.JavaRemoteApplicationLaunchConfigurationDelegate.launch(JavaRemoteApplicationLaunchConfigurationDelegate.java:85) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739) at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039) at org.eclipse.debug.ui.DebugUITools.buildAndLaunch(DebugUITools.java:1025) at com.amazonaws.eclipse.core.util.AbstractApplicationLauncher.launchAsync(AbstractApplicationLauncher.java:53) at com.amazonaws.eclipse.core.util.AbstractApplicationLauncher.launch(AbstractApplicationLauncher.java:60) at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.waitAndLaunchDebugger(SamLocalDelegate.java:186) at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:126) ... 5 more Caused by: com.sun.jdi.connect.spi.ClosedConnectionException at org.eclipse.jdi.internal.connect.SocketTransportService.readHandshake(SocketTransportService.java:222) at org.eclipse.jdi.internal.connect.SocketTransportService.access$7(SocketTransportService.java:214) at org.eclipse.jdi.internal.connect.SocketTransportService$3.run(SocketTransportService.java:185) at java.lang.Thread.run(Thread.java:745) org.eclipse.core.runtime.CoreException: Failed to connect to remote VM at org.eclipse.jdt.internal.launching.SocketAttachConnector.abort(SocketAttachConnector.java:98) at org.eclipse.jdt.internal.launching.SocketAttachConnector.connect(SocketAttachConnector.java:157) at org.eclipse.jdt.internal.launching.JavaRemoteApplicationLaunchConfigurationDelegate.launch(JavaRemoteApplicationLaunchConfigurationDelegate.java:85) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739) at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039) at org.eclipse.debug.ui.DebugUITools.buildAndLaunch(DebugUITools.java:1025) at com.amazonaws.eclipse.core.util.AbstractApplicationLauncher.launchAsync(AbstractApplicationLauncher.java:53) at com.amazonaws.eclipse.core.util.AbstractApplicationLauncher.launch(AbstractApplicationLauncher.java:60) at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.waitAndLaunchDebugger(SamLocalDelegate.java:186) at com.amazonaws.eclipse.lambda.launching.SamLocalDelegate.launch(SamLocalDelegate.java:126) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885) at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739) at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039) at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: com.sun.jdi.connect.spi.ClosedConnectionException at org.eclipse.jdi.internal.connect.SocketTransportService.readHandshake(SocketTransportService.java:222) at org.eclipse.jdi.internal.connect.SocketTransportService.access$7(SocketTransportService.java:214) at org.eclipse.jdi.internal.connect.SocketTransportService$3.run(SocketTransportService.java:185) at java.lang.Thread.run(Thread.java:745)

**Comment by zhangzhx** [comment]
Hey @byamabe , thanks for reaching out to us? I will take a look and fix this in the next release. For a workaround, have you tried relaunch? Do you still see this error message?

**Comment by byamabe** [comment]
@zhangzhx I've tried multiple times and have not seen this error again.

**Comment by zhangzhx** [comment]
Thanks @byamabe, I'm playing with this now trying to reproduce this issue. I'm guessing it's because of the tiny time period between SAM Local takes over the debug port but not ready to attach. I will let you know once this gets fixed.

**Comment by zhangzhx** [comment]
Closing this issue due to no response for a long time. Feel free to reopen it or cut a new one if you still see problems.

Also, we just have launched the [AWS Toolkit for JetBrains](https://plugins.jetbrains.com/plugin/11349-aws-toolkit) with the SAM local debugging support. Feel free to try that out if you want to switch to IntelliJ.
