### ISSUE TITLE
Debug the Lambda function on AWS-SAM-LOCAL in Eclipse

### ISSUE THREAD

**Issue by addictedanshul** [aws/aws-toolkit-eclipse#92]
Followed below steps:
1.	In the Eclipse Project Explorer, open HelloWorldHandler.java.
2.	Right-click in your Eclipse code window, choose Debug As, and then choose AWS SAM Local.
3.	For this example, leave the Project and Template as they are.
4.	Choose Lambda Function in the Run as field.
5.	Choose GetHelloWorld in the Function identifier field.
6.	For this example, we will provide an Amazon S3 event. Choose Generate next to the Event input box.
7.	Choose a region that has your Amazon S3 bucket.
8.	Enter a valid Amazon S3 bucket name.
9.	Enter a valid Amazon S3 object key, and then choose OK.
10.	On the Save As page, select the current project and enter a name for the event file. In this example, we used s3-event.json.
11.	Choose OK to save the event file and get back to the main dialog box.
12.	Leave the advanced settings as they are. See Advanced Settings to learn more about those fields.
13.	Choose Apply, and then choose Debug.
14.	Had also created docker connection in Eclipse Docker Explorer, which connects successfully

-----------------------------------------------------------------------------------------------------------

Eclipse lambda project not able to connect to docker image on my windows system
lambci/lambda:java8

Got below error in eclipse:

[AWS Toolkit] Running command: C:\Users\XXXXXXX\AppData\Roaming\npm\sam.exe local invoke ExampleFunction --debug-port 5858 --event D:\Projects\lambda-worker\src\test\resources\s3-event.put.json --profile default --template D:\Projects\lambda-worker.serverless.template
[AWS Toolkit] Waiting for SAM Local to attach the port 5858
2017/12/22 15:35:56 Successfully parsed D:\Projects\lambda-worker.serverless.template
2017/12/22 15:35:56 Running AWS SAM projects locally requires Docker. Have you got it installed?
2017/12/22 15:35:56 error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[AWS Toolkit] SAM Local invocation done.

**Comment by zhangzhx** [comment]
Hey @addictedanshul, thanks for reaching out to us. From the error message, it seems that you are not running your docker. SAM Local asks for docker to be running as a daemon. See [here](https://github.com/awslabs/aws-sam-local#prerequisites) for detail.

Let me know if you still have this problem after trying running docker in the backend.

**Comment by addictedanshul** [comment]
Hi zhangzhx

My docker daemon is definitely running as I ran it using Docker Quickstart Terminal.

But when I ran "docker ps" from cmd, it gave same error
"//./pipe/docker_engine: The system cannot find the file specified"

I resolved it by running command as below
@FOR /f "tokens=*" %i IN ('docker-machine env') DO @%i

and "docker ps" started giving output
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Now eclipse is also giving same error but I don't know how to resolve it there (screenshot attached).
In eclipse docker explore, I created a connection to my docker daemon as well and it says ping successful.

![aws_error](https://user-images.githubusercontent.com/4507162/34324612-1795e934-e89f-11e7-85b3-b851d60c5178.png)

**Comment by zhangzhx** [comment]
Hey @addictedanshul, I found a similar issue reported here https://github.com/awslabs/aws-sam-local/issues/158. I'm wondering what docker version and SAM version you are using? Can you upgrade to the latest version and try again?

**Comment by addictedanshul** [comment]
Hi @zhangzhx I am using latest SAM 0.2.4 and
Docker version 17.10.0-ce, build f4ffd25

The issue you referenced has been marked resolved in 0.2.3 but I am still getting the same in 0.2.4

Secondly, I am also able to resolve the error when running from cmd, using below command
@for /f "tokens=*" %i IN ('docker-machine env') DO @%i

It is in Eclipse where I am still getting the same error (screenshot attached in previous post.)

**Comment by kpjofficial** [comment]
Hi, I am facing the same error. 

Logs attached.

![image](https://user-images.githubusercontent.com/5809146/51602833-f8393980-1f2d-11e9-8c96-5b041ee42ccd.png)

**Comment by phijacobs** [comment]
@kpjofficial When I received the exception above, the console output in Eclipse contained the attached sam error:

[error.txt](https://github.com/aws/aws-toolkit-eclipse/files/2948705/error.txt)

To resolve it, I created a ~/.aws/config file with the desired region.

@zhangzhx it seems like issue #86 has been addressed but requires the ~/.aws/config file now.

**Comment by phijacobs** [comment]
@kpjofficial it looks like this exception happens even when the ~/.aws/config file exists, so I created a pull request.
