### ISSUE TITLE
Invalid AWS Lambda Project when implementing RequestStreamHandler

### ISSUE THREAD

**Issue by FranciscoHanna** [aws/aws-toolkit-eclipse#96]
I have a Lambda function in Java with a class that implements the `RequestStreamHandler` instead of the `RequestHandler`. When trying to deploy the Serverless Project (using AWS Toolkit right clicking the project in Eclipse's project explorer) it says:

> #### Invalid AWS Lambda Project
>  No Lambda function handler class is found in the project. You need to have at least one concrete class that implements the 
> com.amazonaws.services.lambda.runtime.RequestHandler interface.

I don't think it makes a lot of sense since i'm implementing the `requestHanlder` method that a Lambda function requires as an entrypoint. 

The workaround i'm using right now is to implement both interfaces but leaving the implementation of `RequestHandler` methods empty. This lets me deploy using the toolkit, but it doesn't feel right. 

Any ideas on this topic?

**Comment by zhangzhx** [comment]
Thanks for reporting this. A fix will be released in the next version.

TBH, the ultimate definition for a Lambda function handler in Java is [here](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-handler-types.html). It doesn't even need to implement the `RequestHandler` interface. You can configure the handler in serverless template in this way `fully.qualified.class.name.ClassName::handlerMethod`. And same goes to the `StreamRequestHandler`.

For a long term, we'll add more support in the Eclipse toolkit to make it smarter for recognizing Lambda functions.

**Comment by zhangzhx** [comment]
This fix has been included in the [release](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201801042359). Thanks for the request.

**Comment by kinvercol** [comment]
As of today's date I have the latest release, but still the plug-in doesn't recognise RequestStreamHandler as a valid interface for a Lambda function.
