### ISSUE TITLE
Lambda Memory Size

### ISSUE THREAD

**Issue by tauriello** [aws/aws-toolkit-eclipse#98]
![screen shot 2018-01-05 at 11 10 18 pm](https://user-images.githubusercontent.com/5930522/34636382-a6e30068-f26d-11e7-8159-ff790d16dc23.png)

Increase Lambda upload memory size to Amazon's updated 3008 MB

**Comment by zhangzhx** [comment]
This should be fixed in the latest release. See

https://github.com/aws/aws-toolkit-eclipse/commit/1ffe7b856ff159ef1c444aeeba0c0f53da8e9f47#diff-e0c2d1e2c25f80dcf7e52a9ba4179997R75

Please update to version [v201801042359 ](https://github.com/aws/aws-toolkit-eclipse/releases/tag/v201801042359)
